aya-prover/aya-dev

cli/src/main/java/org/aya/cli/repl/Repl.java
cli/src/main/java/org/aya/cli/repl/command/CommandArg.java
cli/src/main/java/org/aya/cli/repl/jline/AyaReplParser.java
cli/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli/src/main/java/org/aya/cli/repl/jline/completer/AyaCompleters.java
cli/src/test/java/JlineTest.java

This adds back completion for `(Ty <tab>` and also supports path completion.

REPL: choose parser by param type (currently only Path.class uses a shell like parser)

---

base/src/main/java/org/aya/concrete/desugar/BinOpSet.java
base/src/main/java/org/aya/concrete/resolve/ResolveInfo.java
base/src/main/java/org/aya/concrete/resolve/module/FileModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/tyck/order/IncrementalTycker.java
base/src/main/java/org/aya/tyck/order/SCCTycker.java
base/src/test/java/org/aya/concrete/VisitorTest.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
tools/src/main/java/org/aya/util/MutableGraph.java

In the past, we will stop tycking immediately when a statement fails. Now we can skip the failed statement and its dependents and try to tyck as much as possible and always produce a `wellTyped` list, which is quite good for our LSP frontend.

Tyck of one SCC will not be interrupted by unrelated failed SCCs

---

buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
cli/src/main/java/org/aya/cli/repl/Repl.java

fix `-`, `;` or chars not listed in AyaLexer.g4 will case token recoginition error

Handle token recognition error in REPL

---

base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/resources/failure/tyck/nonstruct-new.aya.txt
pretty/src/main/java/org/aya/pretty/doc/Doc.java

Print `new` expressions as blocks

---

base/src/main/java/org/aya/concrete/parse/AyaProducer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/resources/failure/patterns/selection-failure.aya.txt
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
parser/build.gradle.kts

Summary:
+ 🍒-picked @imkiva's commit from #191 for projection tycking
+ Added hint for index unification failure
+ Simplified grammar
+ Added a TODO for index unification failure in pat classifier. Basically, if we are splitting with clauses present and we cannot decide if we want to split on one of the constructors, we report an error.
bors r+

Enhance something

---

base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/core/def/CtorDef.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/test/resources/failure/patterns/unsure-missing.aya
base/src/test/resources/failure/patterns/unsure-missing.aya.txt
base/src/test/resources/success/redblack.aya
lsp/src/main/java/org/aya/lsp/server/AyaService.java
tools/src/main/java/org/aya/util/ArrayUtil.java

Summary:
+ Added `ArrayUtil` 🍒-picked from `arrays` branch (#192)
+ Now index unification failure in constructor selection (in coverage checker) is taken carefully: if the failure is due to a stuck case and there aren't any catch-all patterns, we report an error. (in case there are no patterns, we do not report error, as this will eventually become either an impossible case or a missing case)
+ Added indexed redblack tree (I blame @dramforever for pushing me to do this, it took me the entire afternoon!! But I also appreciate it as this helped me discovering all these bugs)
+ Since `ownerTele` in `CtorDef` isn't equal to the corresponding `DataDef.telescope()` (so in case core of a concall is missing, we can't retrieve `ownerTele`!! This is impossible yet, but may once become possible). To …

Enhance error report for rbTree

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/core/term/ElimTerm.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/resources/failure/patterns/issues/issue681.aya.txt

Fix #195.
Summary:
+ Blocks (conditions and `new` expression body) in concrete are now pretty printed with alignment and indentation
+ Pi type in core is now pretty printed in the beautiful way (nested pi will be shortened)
+ `AppTerm` and `AppExpr` has `unapp` implemented totally wrongly and are now fixed
bors r+

Pretty printing enhancements

---

base/src/main/java/org/aya/concrete/parse/AyaParsing.java
base/src/main/java/org/aya/concrete/parse/AyaProducer.java
base/src/main/java/org/aya/concrete/resolve/module/CachedModuleLoader.java
base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/java/org/aya/test/LibraryTest.java
base/src/test/java/org/aya/tyck/TyckDeclTest.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/library/LibrarySource.java

A simple fix of #228 
This PR adds two field to `LibrarySource`
- `Ref<ImmutableSeq<Stmt>>` as concrete trees which is initialized after resolving library imports
- `Ref<ResolveInfo>` which I don't know whether can be reused by LSP (if not, we remove it then)

Reuse parsed tree instead of import only

---

base/src/main/java/org/aya/concrete/resolve/ResolveInfo.java
base/src/main/java/org/aya/concrete/resolve/error/PrimDependencyError.java
base/src/main/java/org/aya/concrete/resolve/error/RedefinitionPrimError.java
base/src/main/java/org/aya/concrete/resolve/error/UnknownPrimError.java
base/src/main/java/org/aya/concrete/resolve/module/ModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtShallowResolver.java
base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/tyck/order/AyaOrgaTycker.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/test/resources/failure/scope/issue274.aya.txt
base/src/test/resources/failure/scope/prim-dependency.aya.txt
base/src/test/resources/failure/scope/re-prim.aya.txt
base/src/test/resources/failure/scope/unknown-prim.aya.txt
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

Summary
- remove `OpInfo` from `PrimDecl` because we don't have a proper way of using prims as operators #289 .
- resolve `PrimDecl` in the shallow resolver, which creates `PrimDef` instances from concretes' `DefVar`.
- set all dependencies of prims in `PrimDef` because we need `DefVar` to create it which is only accessible by declaring prim names explicitly.
- other refactorings related to resolving and parsing

Resolve prim in shallow resolver

---

.github/README.md
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
cli/src/main/java/org/aya/cli/library/source/LibrarySource.java
lsp/src/main/java/org/aya/lsp/actions/ComputeSignature.java
lsp/src/main/java/org/aya/lsp/actions/ComputeTerm.java
lsp/src/main/java/org/aya/lsp/actions/FindReferences.java
lsp/src/main/java/org/aya/lsp/actions/GotoDefinition.java
lsp/src/main/java/org/aya/lsp/actions/Rename.java
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/server/AyaServer.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
lsp/src/main/java/org/aya/lsp/utils/ModuleVar.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

This PR improved existing features:
- Binding emission logic for better hover messages
- Find references in pattern matchings and projections
- Position resolver now correctly finds all `Var`s (we cannot resolve ctors, fields and local telescopes if the cursor was placed at the name part of their definitions before)
and introduced new features:
- Rename a symbol
- Highlight all occurrences of a text by scoping rule (instead of string comparison!!)
- Goto definition for import commands (close #291)
and generalized some tools for future IDE development:
- The `Resolver` class which handles concrete term interactions (all features mentioned above heavily depend on this _busybox_)
- The `ModuleVar` for expanding the definition-based mechanism to modules (like goto module, rename module, etc.)

Now I can play with Aya in VSCode happily

---

api/src/main/java/org/aya/api/error/CollectingReporter.java
api/src/main/java/org/aya/api/error/CountingReporter.java
api/src/main/java/org/aya/api/ref/DefVar.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/resolve/module/ModuleLoader.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

- Fixed not clearing reporter countings when one definition failed to tyck (which causes all coming definitions to be treated as failed)
- Search both core and concrete term when highlighting
- Skip `DefVar`s from skipped modules and libraries

Fix a critical bug of SccTycker

---

api/src/main/java/org/aya/api/ref/DefVar.java
base/src/main/java/org/aya/concrete/remark/Remark.java
base/src/main/java/org/aya/concrete/stmt/Command.java
base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/concrete/stmt/Generalize.java
base/src/main/java/org/aya/concrete/stmt/Sample.java
base/src/main/java/org/aya/concrete/stmt/Signatured.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/main/java/org/aya/tyck/order/TyckUnit.java
base/src/test/resources/success/common/src/Refparo/Model.aya

Check `needTyck` with current module name so imported definitions won't pollute `CompiledAya`

Call `needTyck` with current module name

---

cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/library/source/DiskLibraryOwner.java
cli/src/main/java/org/aya/cli/library/source/LibraryOwner.java
lsp/src/main/java/org/aya/lsp/library/WsLibrary.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

When debugging #312 I found the reporter in library owner was not used and caused the compiler to skip writing core files for modules followed. It turns out some changes have been made to make the delayed reporter in the library compiler not working, which is mostly due to my careless reviewing of https://github.com/aya-prover/aya-dev/commit/b10d16ad26d5197836d992af378be0b4bdce2c71 which implicitly breaks the fixture in https://github.com/aya-prover/aya-dev/commit/c7b3ade253bff180ad2daf059e54f6c1a4e65add
hit hit kiva

Remove reporter from library owner

---

base/src/test/resources/success/src/Structs.aya
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

This PR fixes #168 
Added a new rule of expr
```diff
expr : atom                                 # single
| expr argument+                       # app
| NEW_KW expr LBRACE newArg* RBRACE    # new
+     | NEW_KW expr                          # newEmpty
```
rather than simply make the block part optional like this
```diff
expr : atom                                 # single
| expr argument+                       # app
-     | NEW_KW expr LBRACE newArg* RBRACE    # new
+     | NEW_KW expr (LBRACE newArg* RBRACE)? # new
```
This is because in the latter change for given code `new T {}` the antlr always matches the `{}` with the `expr` and treats the following as optional because there's a `{ exprList }` in `argument`. 
And we should allow both `new T` and `new T {}` for empty records for …

Allow empty `new` block

---

base/src/main/java/org/aya/resolve/visitor/StmtResolver.java

Fixed assertion error when compiling [Reflection.aya](https://github.com/aya-prover/aya-dev/blob/tactic/base/src/test/resources/success/common/src/Data/Reflection.aya)

Constructors and fields should explicitly depend on their top-level decls.

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/tyck/stringlit-1.aya.txt
base/src/test/resources/failure/tyck/stringlit-2.aya.txt
base/src/test/resources/failure/tyck/stringlit-3.aya.txt

The `default -> unifyTyMaybeInsert(term, synthesize(expr), expr);` is eligible for:
- checking the string literal
- solving the meta to string type (allowing this code `def a => "hello"`)
so,
bors merge

Remove check of string literal from ExprTycker and add test output

---

base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/test/resources/failure/patterns/confl-literal.aya
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/success/src/Literal.aya

We used to convert literals to constructor forms when classifying them, so it's possible to overflow the stack if the literal was too large. 
But when classifying literal patterns together with other patterns, literal patterns will be converted to constructor forms whenever there are remaining constructor patterns, for example, when calling `classify([20, suc a])`, the patterns below
```
20 => 
suc a =>
```
will be treated as
```
suc 19 =>
suc a =>
```
So we put them in an `MCT.Node` and remove their heads to form the next-step-patterns `[19, a]` and recursively call `classify([19, a])`, which may cause StackOverflow if the literal 19 becomes larger.
It's easy to find the optimizable case: there always exists a scenario that **the patterns to be classified in the next step has only two …

Optimize `PatClassifier` for literals

---

base/src/main/java/org/aya/concrete/visitor/ExprView.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java

Fixed a problem where distilling `{? expr ?}` may cause NPE

Pass `accessibleLocal` to fix NPE

---

buildSrc/src/main/groovy/org/aya/gradle/GenerateVersionTask.groovy
lsp/build.gradle.kts

So that `jlink` is reexecuted when base or cli are recompiled.

Properly configure the inputs of prepareMergedJarsDir

---

.github/README.md
base/src/main/java/org/aya/terck/CallResolver.java
base/src/test/resources/success/src/FoetusLimitation.aya

fix #471
After days of digging into agda's codebase (most of the time was spent on setting up a haskell ide) I finally know the differences between foetus in paper and foetus in agda. I decide to bring them to aya after composing some conclusion notes.
The `FoetusLimitation.aya` test is only removed temporarily. We will see it back sooner or later 😉

Be strict when comparing constructors for termination

---

base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
gradle/deps.properties
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/latex/TeXStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinterConfig.java
pretty/src/main/java/org/aya/pretty/backend/string/StringStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/style/ClosingStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/style/DebugStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/style/UnixTermStylist.java
pretty/src/main/java/org/aya/pretty/printer/PrinterConfig.java
pretty/src/main/java/org/aya/pretty/printer/Stylist.java
pretty/src/main/java/org/aya/pretty/style/AyaColorScheme.java
pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java

As said in the commit messages, I've added a new theme and it's randomly used in the codebase now.
I've refactored `PrinterConfig` and inheritors so that color schemes and styles are now taken from some constructor calls instead of in the deepest constructor overload of `Stylist`.
Anybody wanna make the color themes configurable?
bors r+

IntelliJ theme

---

base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/IntroTerm.java
base/src/main/java/org/aya/core/term/StableWHNF.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/DeltaExpander.java
base/src/main/java/org/aya/core/visitor/EndoFunctor.java
base/src/main/java/org/aya/core/visitor/Expander.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
build.gradle.kts

Introduce the `DeltaExpander` and `BetaExpander` interface to separately handle delta- and beta-reduction.
The `Expander` interface is now extending both `DeltaExpander` and `BetaExpander`.
Some unresolved issues:
1. I'm not sure how to classify operations on the cubical types as beta/delta reduction.
(See the static methods in each interface for the current arrangement)
2. There is a `Simplifier` visitor implementing `BetaExpander` that only do beta reduction.
Maybe we need to change `Substituter` to use this new visitor as per #451?
Edit (@ice1000): fix #451 as the code is pretty clear and good. The cubical reductions are classified as beta, and simplifier is superseded by the substitutor. I added `StableWHNF` for cubically stable term formers, see javadoc.

Refactor: Separate delta and beta reduction.

---

lsp/src/main/java/org/aya/lsp/server/AyaServer.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

fix
```
Caused by: java.lang.UnsupportedOperationException
at org.aya.prover.merged.module@0.21-SNAPSHOT/org.eclipse.lsp4j.services.LanguageServer.getNotebookDocumentService(Unknown Source)
... 23 more
The language server exited with 0 (null)
```

Workaround a lsp4j bug

---

base/src/test/resources/success/common/src/Paths.aya
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

@imkiva @lunalunaa is it a good idea to allow `[| i |] A` as a shorthand for `[| i |] A {| |}`?
P.S. I miss GK bc they generate nullability annotations.

Allow empty system

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
gradle/deps.properties
tools-repl/src/main/java/org/aya/repl/gk/JFlexAdapter.java

New methods:
* `Seq.generateUntil(Supplier<E>, Predicate<E>)`
* `Seq.generateUntilNull(Supplier<E>)`

KALA: upgrade to 0.52.0

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/PrimTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/LittleTyper.java

Implement the following primitives:
I will ignore the subtype checks before cubical subtype is implemented in another PR. After cubical subtype is finished we just need to change the signatures and add proper `inS` and `outS`.
TODO: explore ways to automatically insert `inS` and `outS`.
**Update (2022 Oct 23): `coeFill`, `coeInv`, `coeFillInv`, `forward`, `hfill`, `comp` will not be implemented as primitives. Instead they are helper functions**
This pull request closes #522, #525.

transport and hcomp

---

base/reflect-config.txt
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/DummyTerm.java
base/src/main/java/org/aya/core/term/ElimTerm.java
base/src/main/java/org/aya/core/term/ErasedTerm.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/generic/SortKind.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/ErasedError.java
base/src/test/resources/failure/tyck/erased.aya
base/src/test/resources/failure/tyck/erased.aya.txt
base/src/test/resources/success/src/Prop.aya
base/src/test/resources/success/src/Sorts.aya

This pr
+ Added ErasedTerm
+ generate ErasedTerm on inherit/synthesize whenever sort is Prop
+ implement illegal erased term check.
+ add a reduction rule: `elim(erased)` become `erased`
+ corrected prop-related tyck rules for sigma types and struct
+ updated LittleTyper to support new universe system for `type.computeType()` use cases

Prop and Erased

---

base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/patterns/literal-conf.aya
base/src/test/resources/failure/patterns/literal-conf.aya.txt
base/src/test/resources/failure/syntax/issue164.aya.txt
base/src/test/resources/failure/tyck/issues/issue697.aya.txt
base/src/test/resources/success/src/Issues/495.aya
base/src/test/resources/success/src/Sorts.aya

Hoshino Tented
We cannot solve metas in result type from clauses, because when we're in the clauses, the result type is substituted, and it doesn't make sense to solve a "substituted meta"
In the future, we may generate a "constant" meta and try to solve it if the result type is a pure meta.

Cherry pick from @HoshinoTented's branch

---

base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/pat/TypedSubst.java

The _subst of parameters of Ctor_ now disappear after tyck that `Pat.Ctor`. For example:
```aya
open data Nat
| O
| S (_1 : Nat)
def justMatch (m n : Nat) : Nat
| O, n => O
| S m', n => m'
```
There is a subst `_1 |-> m'` when we tyck the  `n` pattern in `| S m', n => m'`, which is useless.

No more useless subst

---

base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatMatcher.java
base/src/main/java/org/aya/core/visitor/PatTraversal.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/holes/no-more-var.aya
base/src/test/resources/failure/holes/no-more-var.aya.txt
base/src/test/resources/success/src/MetaInMeta.aya

This PR allows this code compiles:
```aya
open data Nat | O | S Nat
open data INat (n : Nat)
| O => zero
| S n' => +-one
| S (S n') => +-two
def yes {n : Nat} (a : INat n) (b : INat n) : Nat
| +-one, +-two => O
| _, _ => S O
```
The `yes` function is equivalent to:
```aya
def yes {n : Nat} (a : INat n) (b : INat n) : Nat
| {S (S n')}, +-one, +-two => O
| {n}, _, _ => S O
```

Pat.Meta in Pat.Meta

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/test/resources/failure/tyck/erased2.aya
base/src/test/resources/failure/tyck/erased2.aya.txt

TODO:
+ Generate ErasedTerm for pattern matching

Implement Prop pattern matching tyck

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/resolve/error/PrimResolveError.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/test/java/org/aya/core/NormalizeTest.java
base/src/test/java/org/aya/core/SuedeTest.java
base/src/test/resources/failure/syntax/bad-prim-usage.aya
base/src/test/resources/failure/syntax/bad-prim-usage.aya.txt
base/src/test/resources/failure/syntax/literate-unresolved.aya
base/src/test/resources/failure/syntax/literate-unresolved.aya.txt
base/src/test/resources/failure/tyck/issues/issue697.aya
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/src/Refparo/Model.aya

this is done by rejecting references to `coe` in the resolver.

Disallow using `coe` as function

---

base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/core/repr/AyaShape.java
base/src/main/java/org/aya/core/repr/CodeShape.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/test/java/org/aya/repr/ShapeMatcherTest.java
base/src/test/resources/failure/syntax/implicit-element-list-pattern.aya
base/src/test/resources/failure/syntax/implicit-element-list-pattern.aya.txt
base/src/test/resources/success/src/List2.aya
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java

A re-development of #599 on the new base.

Allowing Implicit Argument in List Ctor

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/term/CoeTerm.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/common/src/Primitives.aya
base/src/test/resources/success/src/CubicalBasics.aya
base/src/test/resources/success/src/Refparo/Demo.aya

This PR also changed signature of `coeFill` and `coeInvFill` to:
- `coeFill (A : I -> Type) (phi : I) : Pi (u : A 0) -> Path A u (coe A phi u)`
- `coeInvFill (A : I -> Type) (phi : I) : Pi (u : A 1) -> Path (\i => A (~ i)) u (coeInv A phi u)`
so they are desugared in the same way as `coe` and `coeInv`:
- `coe (A : I -> Type) (phi : I) : A 0 -> A 1`
- `coeInv (A : I -> Type) (phi : I) : A 1 -> A 0`

Constant check for `coeFill`, `coeInv` and `coeInvFill`

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/src/Order.aya

by using `Def.defTele(ref)` over `ref.core.telescope()`

Fix tycking induction-recursion definitions

---

.github/README.md
base/src/test/resources/success/common/src/Arith/Nat/Core.aya
base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
base/src/test/resources/success/common/src/Data/List/Core.aya
base/src/test/resources/success/src/Issues/14.aya
base/src/test/resources/success/src/NatMonoid.aya

Including the readme, the library.
bors r+

Minor improvements

---

cli/src/main/java/org/aya/cli/render/RenderOptions.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/repl/ReplShapeFactory.java
cli/src/main/java/org/aya/cli/repl/gk/GKReplLexer.java
cli/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli/src/test/java/org/aya/cli/JlineReplTest.java
tools-repl/build.gradle.kts
tools-repl/src/main/java/module-info.java
tools-repl/src/main/java/org/aya/repl/CommandArg.java
tools-repl/src/main/java/org/aya/repl/ReplHighlighter.java
tools-repl/src/main/java/org/aya/repl/ReplLexer.java
tools-repl/src/main/java/org/aya/repl/ReplParser.java

and highlight keywords using colors from configured color scheme...
and fix #683

REPL: decouple and fix

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/Tycker.java
base/src/test/resources/success/common/src/Arith/Int.aya
base/src/test/resources/success/common/src/Spaces/Susp.aya
lsp/build.gradle.kts
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/models/HighlightResult.java

Fix a bug: HIT partial forgot to zonk

---

base/src/main/java/org/aya/generic/Constants.java
base/src/main/java/org/aya/ref/LocalVar.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli/src/test/java/org/aya/cli/HighlighterTest.java
cli/src/test/java/org/aya/cli/HighlighterTester.java

There are some problems with `Highlighter`
* `Expr.Param#ref`s didn't highlight (so no definitions)
* For the parameters that share the same type, like `(a b : A)`, the type will be highlighted twice, we can perform `.distinct` after `.sort` to solve this problem

Fix Highlighter

---

cli/src/main/java/org/aya/cli/library/json/LibraryConfigData.java

It is already in `asConfig(@NotNull Path libraryRoot, @NotNull Function<String, Path> buildRootGen)`

cli: remove a duplicate checkDeserialization() call

---

base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/resources/success/common/src/Algebra/Formula.aya
base/src/test/resources/success/common/src/Arith/Int.aya
base/src/test/resources/success/common/src/Arith/Nat/Core.aya
base/src/test/resources/success/common/src/Arith/Nat/Order.aya
base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
base/src/test/resources/success/common/src/Data/List/Core.aya
base/src/test/resources/success/common/src/Logic/False.aya

Improve library with pushing

---

base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/ref/DefVar.java
base/src/test/java/org/aya/core/DistillerTest.java

(partially) fixes https://github.com/aya-prover/aya-dev/issues/687
leftovers:
+ print `¬ ¬ A` instead of `¬ (¬ A)`

basic support for unary pretty print

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/core/term/PAppTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/src/CubicalBasics.aya
lsp/build.gradle.kts

Well, only for simplest cases.

Implement coercion from path to pi

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/term/LamTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/tyck/issues/issue697.aya.txt
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/src/CubicalBasics.aya

Really do support eta-expand paths

---

base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
gradle/deps.properties
lsp/src/test/java/org/aya/lsp/LspTest.java

New features:
* `CollectionLike::distinct()`
* `CollectionLike::zip(Iterable<U>, BiFunction<E, U, R>)`
* `Traversable::mapToIntTo(IntGrowable, ToIntFunction<E>)`

KALA: upgrade to 0.57.0

---

base/src/main/java/org/aya/terck/CallResolver.java
base/src/test/resources/success/src/FoetusLimitation.aya
base/src/test/resources/success/src/Mutual.aya
base/src/test/resources/success/src/Termination.aya

Aya rejects
```aya
def just-pred (n : Nat) : Nat => pred n
def pred Nat : Nat
| zero => zero
| suc n => just-pred n
```

Fix a serious termination check bug

---

base/src/main/java/org/aya/concrete/visitor/ExprFolder.java
base/src/main/java/org/aya/concrete/visitor/PatternFolder.java
base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
base/src/main/java/org/aya/tyck/ExprTycker.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

This allows finer grain control on the handling of variables, which we can now distinguish between variable declaration and reference.
The first commit solves an immediate design problem noticed by @HoshinoTented.
I've then noticed some duplicated logic that can be better handled by the new API in the LSP highlighter and resolver.
If no one is working on that part of the code currently, I can clean that up in a follow up commit.

Update Folder in the concrete layer.

---

base/src/main/java/org/aya/concrete/remark/Literate.java
cli/src/main/java/org/aya/cli/literate/LiterateConsumer.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java

this enables "jump to definition" for all names in vitepress

Properly escape css selectors

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/test/resources/failure/patterns/issues2/issue775.aya
base/src/test/resources/failure/patterns/issues2/issue775.aya.txt
base/src/test/resources/success/src/Match.aya

- Gate away the reachable match arms with empty body from passing type-checking:
- Check: for those patterns used in elimination (rather than data decl), if Pattern.Absurd () does not appear on lhs, then we require a body
close #775

fix(pattern): add check for absurd patterns

---

base/src/test/resources/failure/operator/no-assoc.aya.txt
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-confl.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-reduce.aya.txt
base/src/test/resources/failure/patterns/issues/issue366.aya.txt
base/src/test/resources/failure/patterns/issues2/issue597.aya.txt
base/src/test/resources/failure/patterns/issues2/issue775.aya.txt
base/src/test/resources/failure/patterns/issues2/issue99-1.aya.txt
base/src/test/resources/failure/patterns/issues2/issue99-2.aya.txt
base/src/test/resources/failure/patterns/literal-conf.aya.txt
base/src/test/resources/failure/scope/did-you-mean-disamb.aya.txt
base/src/test/resources/failure/syntax/issue164.aya.txt
base/src/test/resources/failure/tyck/erased.aya.txt
base/src/test/resources/failure/tyck/issues/issue300.aya.txt
base/src/test/resources/failure/tyck/nonsigma-proj.aya.txt
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/main/java/org/aya/pretty/error/PrettyError.java

fix #805 
Just fixed the case with `Doc.english`, you can still construct a counterexample with `Doc.sep(Doc.plain(), Doc.plain(), ...)`

Partially fix page width problem

---

gradle/deps.properties

New module : `org.glavo.kala:kala-common-gson`
Usage:
```java
var gson = KalaGson.registerKalaTypeAdapters(new GsonBuilder()).create();
```

KALA: upgrade to 0.59.0

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/error/ParseError.java
base/src/main/java/org/aya/tyck/unify/Synthesizer.java
base/src/test/resources/failure/syntax/implicit-element-list-pattern.aya.txt
base/src/test/resources/failure/syntax/incomplete-code.aya
base/src/test/resources/failure/syntax/incomplete-code.aya.txt
base/src/test/resources/failure/syntax/issue164.aya.txt
base/src/test/resources/failure/syntax/issue165.aya.txt
base/src/test/resources/failure/syntax/literal-too-large.aya.txt
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Addresses a privately reported issue from @SchrodingerZhu 
bors r+

More robust parsing

---

base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/ConCall.java
base/src/main/java/org/aya/core/term/SigmaTerm.java
base/src/main/java/org/aya/core/visitor/EndoTerm.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/failure/holes/issue747.aya.txt
base/src/test/resources/success/src/Prop.aya
note/glossary.md

Irrelevance of `Prop` WIP

---

base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/env/MapLocalCtx.java
base/src/main/java/org/aya/tyck/env/SeqLocalCtx.java

There are some problems because of the duplicated vars, why don't we just add an assertion and save our time?

No More Duplicated Vars

---

base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/core/term/SigmaTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/tycker/PropTycker.java
base/src/main/java/org/aya/tyck/unify/Synthesizer.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
tools/src/main/java/org/aya/util/Decision.java

These commits have been in my disk for so long so I have made up my mind to create a PR for them

Random refactoring, preparing for fixing `Prop` tycking

---

base/src/main/java/org/aya/concrete/stmt/ClassDecl.java
base/src/main/java/org/aya/concrete/stmt/CommonDecl.java
base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/concrete/stmt/DeclInfo.java
base/src/main/java/org/aya/concrete/stmt/TeleDecl.java
base/src/main/java/org/aya/concrete/visitor/StmtConsumer.java
base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/main/java/org/aya/core/term/Callable.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/prettier/ConcretePrettier.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/main/java/org/aya/tyck/order/SigRefFinder.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
cli/src/main/java/org/aya/cli/parse/ModifierParser.java
ide/src/main/java/org/aya/ide/action/ComputeSignature.java
tools/src/main/java/org/aya/util/terck/Relation.java

This PR:
+ Removes `Decl.Resulted` and `Decl.Telescopic`
+ Make code use `TeleDecl`
+ Introduce `DeclInfo` for good code reuse.

Cleanup concrete decls: step 0

---

.github/workflows/nightly-build.yml
base/reflect-config.txt
base/src/main/java/org/aya/core/serde/SerDef.java

I genuinely apologize for the quick merge.

Improve scripts for real this time

---

base/src/main/java/org/aya/terck/CallResolver.java
base/src/test/resources/success/common/src/Data/FiniteMultiSet/Core.aya
base/src/test/resources/success/common/src/Logic/SetTrunc.aya

This partially addresses #907. There are two issues left:
+ Unfold some simple decls before tercking. This cannot be done because `TermConsumer` does not allow blocking a sub-tree traversal. /cc @wsx-ucb 
+ Predicativity assumption for `Type`

Predicativity assumption for terck

---

base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/java/org/aya/literate/HighlighterTest.java
base/src/test/java/org/aya/literate/HighlighterTester.java
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/test/java/org/aya/cli/LexerPlayground.java
cli-impl/src/test/java/org/aya/cli/RenderOptionsTest.java
parser/src/main/grammar/AyaPsiLexer.flex
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/style/AyaColorScheme.java
pretty/src/test/java/org/aya/pretty/Reproduction.java
tools-repl/src/main/java/org/aya/repl/ReplHighlighter.java
tools-repl/src/main/java/org/aya/repl/ReplLexer.java
tools-repl/src/main/java/org/aya/repl/ReplParser.java

+ LaTeX backend now generates `~` instead of ` `
+ `\indent{}` instead of `\indent`
+ Improve comment style (hopefully)

Partially address some problems in pretty printer

---

base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/resolve/ResolveInfo.java
base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/context/ModulePath.java
base/src/main/java/org/aya/resolve/context/ModuleSymbol.java

- The keys of `ResolveInfo#imports` and `ResolveInfo#reExports` are now `ModulePath.Qualified` as they should.
- Supports module renaming in `CompiledAya` to fix a TODO.

Fix some potential bugs

---

base/src/test/java/org/aya/literate/AyaMdParserTest.java
cli-console/src/main/java/org/aya/cli/console/Main.java
cli-console/src/main/java/org/aya/cli/console/MainArgs.java
cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
cli-console/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplConfig.java
cli-impl/src/main/java/org/aya/cli/render/RenderOptions.java
cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/main/java/org/aya/cli/utils/CliEnums.java
cli-impl/src/test/java/org/aya/cli/RenderOptionsTest.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/html/HtmlConstants.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/latex/TeXStylist.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinterConfig.java
pretty/src/main/java/org/aya/pretty/backend/terminal/DocTermPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/main/java/org/aya/pretty/printer/PrinterConfig.java

After merging this PR, please add `--pretty-ssr` to [aya-prover-docs](https://github.com/aya-prover/aya-prover-docs/blob/711029dffc6291c51f85756cbc2f7ca3f2fe5516/scripts/build-aya.js#L32).

Literate: KaTeX, ServerSideRendering, and options to inline highlight styles

---

base/src/main/java/module-info.java
base/src/main/java/org/aya/concrete/error/OperatorError.java
base/src/main/java/org/aya/concrete/remark/CodeOptions.java
base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/main/java/org/aya/concrete/remark/code/CodeAttrProcessor.java
base/src/main/java/org/aya/concrete/remark/code/CodeOptions.java
base/src/main/java/org/aya/concrete/remark/math/InlineMath.java
base/src/main/java/org/aya/concrete/remark/math/MathBlock.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/main/java/org/aya/resolve/error/PrimResolveError.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/error/FieldError.java
base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/resources/literate/.gitignore
base/src/test/resources/literate/syntax.aya.md
cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
cli-impl/src/test/java/org/aya/cli/RenderOptionsTest.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/html/HtmlConstants.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/backend/terminal/DocTermPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/main/java/org/aya/pretty/doc/Language.java
pretty/src/test/java/org/aya/pretty/MdStyleTest.java
pretty/src/test/java/org/aya/pretty/Reproduction.java

Example:
```md
Inline math: $\mathrm{type}$.
Math block:
$$
\LaTeX
$$
```
This works with markdown processors that support KaTeX (like Vuepress/Vitepress)

Support LaTeX math formula in literate mode

---

base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/test/java/org/aya/test/LibraryTest.java
base/src/test/resources/failure/syntax/bad-gen-var.aya
base/src/test/resources/failure/syntax/bad-gen-var.aya.txt
ide-lsp/src/test/java/org/aya/lsp/LspTest.java

Fix #972.5

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/generic/Nested.java
base/src/main/java/org/aya/prettier/ConcretePrettier.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/tycker/LetListTycker.java
base/src/main/java/org/aya/tyck/tycker/MockTycker.java

Goals:
+ [x] Nested interface for nested structure (copied from #979)
+ [x] Better prettier for lambda
+ [x] Fixes baka let which has redundant lambda
TODOs:
+ [ ] ~~Better prettier for Pi (if Goal#2 is good)~~ Pi is special

Fix baka let and add some improvement

---

ide-lsp/src/main/java/org/aya/lsp/actions/LensMaker.java
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide/src/main/java/org/aya/ide/action/FindReferences.java

This addresses issue #872. It also affects the "Go to References" function in VSCode.
This doesn't handle mutual recursion, otherwise usage counts would all become 0.

Correctly count usage in recursive definitions

---

.github/workflows/commit-check.yml
.github/workflows/gradle-check.yml
.github/workflows/nightly-build.yml
base/src/main/java/org/aya/concrete/remark/CodeOptions.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/prettier/Codifier.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/DoubleChecker.java
base/src/main/java/org/aya/tyck/unify/Synthesizer.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
build.gradle.kts
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
gradle/wrapper/gradle-wrapper.properties
ide/src/main/java/org/aya/ide/action/GotoDefinition.java
tools-md/src/main/java/org/aya/literate/LiterateConsumer.java

> Full Support for Java 20
> Gradle 8.1 supported compiling and testing with Java 20 using Java toolchains, but running Gradle itself on Java 20 was not yet supported.
> 
> With this release, Gradle now fully supports compiling, testing and running on Java 20.

Bump Gradle to 8.3 RC1

---

base/src/main/java/org/aya/core/term/FormulaTerm.java
base/src/main/java/org/aya/core/term/PartialTerm.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/DeltaExpander.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/prettier/BasePrettier.java
base/src/main/java/org/aya/prettier/Codifier.java
base/src/main/java/org/aya/tyck/tycker/UnifiedTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
tools/src/main/java/org/aya/util/Pair.java

bors r+
Written under the supervision of @imkiva and @HoshinoTented

Use Java 20 language features

---

cli-console/src/main/java/org/aya/cli/console/MainArgs.java
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java

In the past, the literated library is always saved to `<project-root>/build/pretty`. Now we can specify the output location through `--pretty-dir`

Respect `--pretty-dir` for libraries

---

.github/README.md
base/src/main/java/org/aya/concrete/GenericAyaFile.java
base/src/main/java/org/aya/concrete/remark/AyaLiterate.java

Fix highlight lost when converting non-literal file to literal file

---

base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/core/ops/Eta.java
base/src/main/java/org/aya/prettier/BasePrettier.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/env/SeqLocalCtx.java
base/src/main/java/org/aya/tyck/unify/Synthesizer.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/java/org/aya/concrete/ParseTest.java
cli-impl/src/test/java/org/aya/cli/ModifierParserTest.java
ide-lsp/src/test/java/org/aya/lsp/LspTest.java

Replace deprecated first/last/firstOption with getFirst/getLast/findFirst.

Do ReplaceWith

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/test/resources/failure/tyck/not-pi.aya
base/src/test/resources/failure/tyck/not-pi.aya.txt

This PR groups methods in ExprTycker.

Grouping methods in ExprTycker

---

base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/prettier/Codifier.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/java/org/aya/literate/HighlighterTester.java
base/src/test/java/org/aya/test/TestRunner.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli-impl/src/test/java/org/aya/cli/LibraryGraphTest.java
gradle/libs.versions.toml
ide-lsp/src/test/java/org/aya/lsp/LspTest.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
tools-kala/src/main/java/org/aya/util/terck/Relation.java
tools-repl/src/main/java/org/aya/repl/CommandManager.java
tools-repl/src/main/java/org/aya/repl/ReplUtil.java
tools/src/main/java/org/aya/util/Version.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Use Java 21 features

---

cli-console/src/main/java/org/aya/cli/console/Main.java
cli-impl/src/main/java/org/aya/cli/render/RenderOptions.java
cli-impl/src/main/java/org/aya/cli/utils/CliEnums.java
cli-impl/src/test/java/org/aya/cli/RenderOptionsTest.java
pretty/src/main/java/org/aya/pretty/backend/terminal/AdaptiveCliStylist.java

This pull request aims to add a new render target, `ANSI16`, to provide better Discord code block support. It's basically Unix format but without 256-color ANSI codes.
Also introduced a quick fix for CLI not respecting output target when using together with the `--fake-literate` option.

pretty: support ansi16

---

base/src/main/java/org/aya/resolve/module/DumbModuleLoader.java
cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
jit-compiler/src/main/java/org/aya/compiler/FileSerializer.java
jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
jit-compiler/src/test/java/CompileTest.java
jit-compiler/src/test/java/CompileTester.java
jit-compiler/src/test/java/MiscTest.java
jit-compiler/src/test/java/RedBlackTreeTest.java
syntax/src/main/java/org/aya/syntax/concrete/stmt/ModuleName.java
syntax/src/main/java/org/aya/syntax/ref/QName.java
syntax/src/main/java/org/aya/syntax/ref/QPath.java

This PR uses a new version of the class name generator, consider a qualified name: `ayaPackage::ayaFile::subModule::foo`,
where `ayaPackage::ayaFile` is a qualified name to a file-level module, `ayaPackage::ayaFile::subModule` is a qualified name to a sub-level module.
The new generator will produce `$ayaFile$subModule$foo` as the class name of  `ayaPackage::ayaFile::subModule::foo`,
note that `ayaPackage` disappears, since it is a package name.

Refactor the Class Name Generator of Compiler

---

base/src/main/java/org/aya/primitive/ShapeFactory.java
base/src/main/java/org/aya/primitive/ShapeMatcher.java
base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/context/ModuleExport.java
base/src/main/java/org/aya/resolve/context/PhysicalModuleContext.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
cli-impl/src/main/java/org/aya/cli/library/incremental/CompilerAdvisor.java
cli-impl/src/main/java/org/aya/cli/library/incremental/DelegateCompilerAdvisor.java
cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
cli-impl/src/main/java/org/aya/cli/library/incremental/InMemoryCompilerAdvisor.java
cli-impl/src/main/java/org/aya/cli/utils/CompilerUtil.java
cli-impl/src/test/resources/shared/src/arith/Nat.aya
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java
jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
syntax/src/main/java/org/aya/syntax/ref/AnyDefVar.java
syntax/src/main/java/org/aya/syntax/ref/CompiledVar.java
syntax/src/main/java/org/aya/syntax/ref/DefVar.java
tools-kala/src/main/java/org/aya/util/binop/BinOpSet.java

Now we have added:
1. Actual deserialization of modules, including context imports, shapes, and operators
2. Serialize fnShape
3. Context now contain `AnyDefVar`, which equals `DefVar + CompiledVar`
4. The compiler now actually compiles the code, because it was missing `--enable-preview`
5. Shared class loader in library incremental advisor
6. Bug fix in pattern serializer
7. Give correct classpath to compiler
8.

Trying to make library deserialization work

---

base/src/main/java/org/aya/resolve/context/ModuleSymbol.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
cli-impl/src/test/java/org/aya/test/TestRunner.java
cli-impl/src/test/java/org/aya/test/fixtures/ParseError.java
cli-impl/src/test/resources/negative/ParseError.txt
jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
syntax/src/main/java/org/aya/syntax/core/term/Term.java

Cleverly create bind amount, not calculate them upon jIT

---

base/src/main/java/org/aya/normalize/Finalizer.java
base/src/main/java/org/aya/resolve/salt/ExprBinParser.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/tycker/Contextful.java
cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
syntax/src/main/java/org/aya/syntax/ref/MetaVar.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Thanks to @utensil and @HoshinoTented !

Some error report issues reported by Utensil Song

---

cli-console/build.gradle.kts
cli-console/src/main/java/module-info.java
cli-console/src/main/java/org/aya/cli/plct/PLCTReport.java
cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java

How to pretty print a core decl?

Show Information of Definition in Repl

---

base/src/test/java/org/aya/tyck/TyckTest.java
syntax/src/main/java/org/aya/syntax/compile/JitClass.java
syntax/src/main/java/org/aya/syntax/compile/JitMember.java
syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
syntax/src/main/java/org/aya/syntax/core/def/MemberDefLike.java

Jit class cp 2

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/normalize/error/UnsolvedLit.java
base/src/main/java/org/aya/resolve/module/ModuleLoader.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
cli-impl/src/test/resources/success/src/Test.aya
cli-impl/src/test/resources/success/src/TestNoExtraLists.aya
jit-compiler/src/test/resources/TreeSort.aya
syntax/src/main/java/org/aya/syntax/core/term/repr/MetaLitTerm.java

Fix two issues related to arrays and meta lit terms, implement `debug-show-shapes`

---

base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
cli-impl/src/main/java/org/aya/cli/utils/CompilerUtil.java
cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
gradle/libs.versions.toml
note/early-changelog.md
syntax/src/main/java/org/aya/prettier/BasePrettier.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java

Never do `is ConCall con && con.conArgs()`. Always check for `ConCallLike`

Error handling, handle `RuleReducer.Con` in `visibleArgs` in `CorePrettier`

---

flake.lock

Closes #1162 
Update dependencies in the development environment provided by Nix flake.

dev: update flake.lock

---

cli-impl/src/test/java/org/aya/test/literate/AyaMdParserTest.java
syntax/src/main/java/org/aya/syntax/literate/AyaBacktickParser.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java

Bugs like this, also non-Aya inline code blocks are not corrcetly parsed

test: hopefully this fixes all the issues I've seen so far

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
cli-impl/src/test/java/org/aya/test/fixtures/ParseError.java
cli-impl/src/test/java/org/aya/test/fixtures/PatTyckError.java
cli-impl/src/test/resources/negative/ParseError.txt
cli-impl/src/test/resources/negative/PatTyckError.txt
producer/src/main/java/org/aya/producer/AyaProducer.java

Fix #1245, but it reports the same error twice. The reason is probably that when tycking the data body, the con is rechecked. We can find a way to avoid that, but I don't see an easy way right now.

Robustness

---

base/src/main/java/org/aya/tyck/pat/PatternTycker.java
cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
cli-impl/src/main/java/org/aya/cli/single/SingleFileCompiler.java
cli-impl/src/test/java/org/aya/test/LibraryTest.java
cli-impl/src/test/java/org/aya/test/TestRunner.java
producer/src/main/java/org/aya/producer/AyaProducer.java

Only report unimported con when the con is no-arg

---

cli-console/src/main/java/org/aya/cli/console/Main.java
cli-console/src/main/java/org/aya/cli/console/MainArgs.java
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli-impl/src/main/java/org/aya/cli/library/json/LibraryConfig.java
cli-impl/src/main/java/org/aya/cli/library/json/LibraryConfigData.java
cli-impl/src/main/java/org/aya/cli/library/json/LibraryDependency.java
cli-impl/src/main/java/org/aya/cli/library/source/LibrarySource.java
cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
cli-impl/src/test/java/org/aya/test/LibraryTest.java
cli-impl/src/test/java/org/aya/test/cli/LibraryGraphTest.java
cli-impl/src/test/java/org/aya/test/literate/AyaMdParserTest.java
cli-impl/src/test/resources/literate/frontmatter.aya.md
ide-lsp/src/main/java/org/aya/lsp/library/WsLibrary.java
pretty/src/main/java/org/aya/pretty/printer/Printer.java
tools-kala/src/main/java/org/aya/util/more/StringUtil.java
tools-md/src/main/java/org/aya/literate/Literate.java
tools-md/src/main/java/org/aya/literate/LiterateConsumer.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java
tools-md/src/test/java/org/aya/literate/MarkdownTest.java
tools/src/main/java/org/aya/util/reporter/DelayedReporter.java

Allow injecting the literate output with datetime info

---

base/src/main/java/org/aya/resolve/context/NoExportContext.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/PatternResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
cli-impl/src/test/resources/negative/ScopeError.txt
cli-impl/src/test/resources/shared/src/data/list/base.aya
cli-impl/src/test/resources/shared/src/data/list/properties.aya
cli-impl/src/test/resources/shared/src/data/vec/base.aya
cli-impl/src/test/resources/shared/src/data/vec/properties.aya
cli-impl/src/test/resources/shared/src/relation/binary/nat_cmp.aya
syntax/src/main/java/org/aya/generic/Suppress.java

This PR intends to eliminate unnecessary and annoying shadow warnings. However, the following code will not report any shadow warning even if the pattern shadows a local variable of another parameter:
```aya
def test (A : Type) (a : A) : A
| a, A => A
```
This is because we cannot tell the parameter of a pattern, this part is done in PatTycker, but it should can be done in desugarer.

Eliminate Unnecessary Shadow Warning

---

cli-impl/src/test/java/org/aya/test/LibraryTest.java
cli-impl/src/test/java/org/aya/test/TestRunner.java
gradle/libs.versions.toml
producer/src/main/java/org/aya/producer/AyaParserImpl.java
producer/src/main/java/org/aya/producer/flcl/FlclParser.java

More readable negative test expects

---

jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeOptimizer.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeVariable.java
jit-compiler/src/main/java/org/aya/compiler/serializers/ConSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/JitTeleSerializer.java
syntax/src/main/java/org/aya/syntax/compile/JitCon.java
syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java

JIT compiler should generate fewer things

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/primitive/ShapeMatcher.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/IApplyConfl.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
jit-compiler/src/main/java/org/aya/compiler/serializers/FnSerializer.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/def/FnClauseBody.java
syntax/src/main/java/org/aya/syntax/core/def/FnDef.java
tools-kala/src/main/java/org/aya/util/tyck/pat/PatClass.java

This PR simplifies confluence check by using a prefix count array data structure for the clause index in MCTs.
It also stores MCTs in the core, which will be helpful later.

Simplify confluence check

---

cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
syntax/src/main/java/org/aya/prettier/BasePrettier.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java

Implement `:case-tree` in repl

---

jit-compiler/build.gradle.kts
jit-compiler/src/main/java/module-info.java
jit-compiler/src/main/java/org/aya/compiler/free/ArgumentProvider.java
jit-compiler/src/main/java/org/aya/compiler/free/Constants.java
jit-compiler/src/main/java/org/aya/compiler/free/FreeCodeBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/FreeExprBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmArgumentProvider.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmClassBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmCodeBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmExpr.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmJavaBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmOutputCollector.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmUtil.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmVariable.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeExprBuilderImpl.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/VariablePool.java
jit-compiler/src/main/java/org/aya/compiler/serializers/CallKind.java
jit-compiler/src/main/java/org/aya/compiler/serializers/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/TermExprializer.java
jit-compiler/src/test/java/CompileTest.java
jit-compiler/src/test/java/CompileTester.java
syntax/src/main/java/org/aya/syntax/compile/CompiledAya.java

This PR introduces a morphism that targets jvm bytecode, which is much more efficient than java source code. However, jvm bytecode is so low-level and will have a lot of potential problems. We need more tests on this.
I also need more advice about bytecode generation.

Classfile Morphism

---

jit-compiler/src/main/java/org/aya/compiler/AsmOutputCollector.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmClassBuilder.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/ref/ModulePath.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Recursive `buildNested` has made the profiler output harder to read:
After turning it into iteration, it's easier:
The `sourcePosForSubExpr` is taking a lot of time. Shit!

Some profile-guided optimization

---

cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/test/java/org/aya/test/literate/AyaMdParserTest.java
tools-kala/src/main/java/module-info.java
tools/build.gradle.kts
tools/src/main/java/module-info.java
tools/src/main/java/org/aya/util/StringUtil.java
tools/src/main/java/org/aya/util/error/SourceFile.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Caches line positions in `SourceFile`.

Fast LineColumn conversion (for #1301)

---

ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmArgumentProvider.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmClassBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmCodeBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmJavaBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmVariable.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmVariablePool.java

Now the expression evaluator in the debugger works fine, but IDEA still cannot perform step over/into precisely, perhaps we need to supply the line number.

Add some symbol information and misc

---

ide-lsp/src/main/java/org/aya/lsp/actions/LensMaker.java
ide-lsp/src/main/java/org/aya/lsp/actions/SymbolMaker.java
ide-lsp/src/main/java/org/aya/lsp/models/ProjectOrFile.java
ide-lsp/src/main/java/org/aya/lsp/models/ProjectPath.java
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide-lsp/src/test/java/org/aya/lsp/LspTest.java
ide-lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java
ide-lsp/src/test/java/org/aya/lsp/tester/TestCommand.java
ide-lsp/src/test/resources/lsp-test-lib0/aya.json
ide/src/main/java/org/aya/ide/Resolver.java
ide/src/main/java/org/aya/ide/action/FindReferences.java
ide/src/main/java/org/aya/ide/action/GotoDefinition.java
ide/src/main/java/org/aya/ide/action/ProjectSymbol.java
ide/src/main/java/org/aya/ide/action/Rename.java

More lsp changes

---

base/src/test/java/org/aya/tyck/TyckTest.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/asm/AsmCodeBuilder.java

More preparation for plunch

---

.github/HACKING.md
base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
cli-impl/src/test/java/org/aya/test/fixtures/TerckError.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiLexer.flex
parser/src/main/grammar/AyaPsiParser.bnf
producer/src/main/java/org/aya/producer/ModifierParser.java
syntax/src/main/java/org/aya/generic/Modifier.java
syntax/src/main/java/org/aya/syntax/core/term/Term.java
syntax/src/main/java/org/aya/syntax/core/term/marker/StableWHNF.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/PartialTerm.java
tools/src/main/java/org/aya/util/RepoLike.java

Rename keyword `partial` to `nonterminating`

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
jit-compiler/src/main/java/org/aya/compiler/morphism/Constants.java
jit-compiler/src/main/java/org/aya/compiler/serializers/AbstractExprializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/ClassTargetSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/ConSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/InvokeSignatureHelper.java
jit-compiler/src/main/java/org/aya/compiler/serializers/JitTeleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/MatchySerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/MemberSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/PatternExprializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/PatternSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/SerializerContext.java
jit-compiler/src/main/java/org/aya/compiler/serializers/TermExprializer.java
jit-compiler/src/test/java/CompileTest.java
jit-compiler/src/test/java/RedBlackTreeTest.java
syntax/src/main/java/org/aya/syntax/compile/JitCon.java
syntax/src/main/java/org/aya/syntax/compile/JitFn.java
syntax/src/main/java/org/aya/syntax/compile/JitMatchy.java

Currently, our PatternSerializer missing the part of whnf the argument, which may stuck in certain situations. Also, `TermExperialize` is responsible for doing some `Normalizer` work, such as normalizing the argument before `invoke`.
This PR:
+ [x] Add a `UnaryOperator` argument (can be `Normalizer`) to `JitFn#invoke`, `JitMatchy#invoke`, and `JitCon#isAvailable`
+ [x] Use `InvokeSignatureHelper` to handle the change above.

Perform WHNF when pattern matching and invoke

---

cli-impl/src/main/java/org/aya/cli/library/source/LibraryOwner.java

Removed a deprecated function usage which throws a big red warning during build test.

Removed deprecated function usage

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/tycker/AppTycker.java
cli-impl/src/test/java/org/aya/test/fixtures/TailRecError.java
cli-impl/src/test/resources/negative/ParseError.txt
cli-impl/src/test/resources/negative/TailRecError.txt
gradle/libs.versions.toml
parser/src/main/java/org/aya/parser/AyaParserDefinitionBase.java
producer/src/main/java/org/aya/producer/AyaProducer.java
producer/src/main/java/org/aya/producer/error/BadXWarn.java

Implement the semantics of the `inline` modifier

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
cli-impl/src/test/resources/success/src/Pattern.aya
tools-kala/src/main/java/org/aya/util/tyck/pat/ClassifierUtil.java

Fixes #1380.
`LhsResult` separates `missingPats` (constructed after tyck patterns) and `tyckedPats` (produced by pattern tycker) from `freePats` and gets rid of `unpiParamSize`.

Try Fix #1380 in a compatible way
