base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/java/org/aya/experiments/ZzsSolver.java

Level solver counterexample construction

---

.github/workflows/gradle-check.yml
bors.toml

Try to disable jlink testing on PRs

---

.github/workflows/gradle-check.yml

Retry disabling non-main jlink builds

---

.github/workflows/gradle-check.yml
base/src/main/java/org/aya/core/sort/Sort.java
base/src/main/java/org/aya/tyck/unify/level/LevelSolver.java
base/src/test/java/org/aya/experiments/ZzsSolver.java
base/src/test/java/org/aya/util/UtilTest.java
base/src/test/resources/success/issues2/issue19.aya
base/src/test/resources/success/refparo/refparo12.aya

Levels bug fix

---

base/src/main/java/org/aya/tyck/error/LevelMismatchError.java
base/src/test/resources/failure/levels/refparo5.aya.txt

Improve level solver error message

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
README.md
bors.toml

All current contributors are encouraged to review the contribution guideline and  propose necessary addition.
Will not be merged before appoval of @ice1000, @imkiva and @Glavo.

Add contribution guideline and code of conduct

---

.github/README.md

Enhance readme

---

base/src/main/java/org/aya/core/serde/SerLevel.java
base/src/main/java/org/aya/core/sort/Sort.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/generic/Level.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/main/java/org/aya/tyck/unify/level/LevelEqnSet.java
base/src/main/java/org/aya/tyck/unify/level/LevelSolver.java
base/src/test/java/org/aya/experiments/ZzsSolver.java

Remove the OMEGA universe and infinity level

---

build.gradle.kts

Set vendor in build script

---

base/src/main/java/org/aya/core/Meta.java
base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/issues2/issue69.aya

Thin white duke?

---

.github/README.md

Fix relative links

---

cli/src/main/java/org/aya/cli/repl/command/CommandArg.java
cli/src/main/java/org/aya/cli/repl/jline/completer/AyaCompleters.java

Simplify the code

---

gradle/deps.properties
note/early-changelog.md

Bump version to 0.11, update changelog

---

base/src/main/java/org/aya/core/visitor/Zonker.java
base/src/main/java/org/aya/generic/Constants.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/holes/ctor-condition.aya.txt
base/src/test/resources/failure/holes/issue747.aya.txt
base/src/test/resources/failure/holes/pattern-confluence.aya.txt
base/src/test/resources/failure/holes/scope-check.aya.txt
base/src/test/resources/failure/holes/ulf-hole-illtype.aya.txt
base/src/test/resources/failure/implicit/implicit2.aya.txt
base/src/test/resources/failure/tyck/issues2/issue34.aya.txt

Useful unsolved meta message

---

api/src/main/java/org/aya/api/distill/DistillerOptions.java
base/src/main/java/org/aya/core/term/IntroTerm.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/resources/failure/tyck/issues/issue697.aya.txt
base/src/test/resources/literate/standard-test.txt
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java

Improve PP

---

base/src/main/java/org/aya/concrete/resolve/error/AmbiguousNameError.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/FieldProblem.java
base/src/test/resources/failure/tyck/issues2/issue151.aya
base/src/test/resources/failure/tyck/issues2/issue151.aya.txt
cli/src/main/java/org/aya/cli/repl/Repl.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/style/EmacsColorScheme.java
pretty/src/test/java/org/aya/pretty/Reproduction.java

Fix #151: added error message
Fix #149: remove ill-typed definitions from context

Fix some issues, improve l∀t∃x backend

---

api/src/main/java/org/aya/api/error/SourceFile.java
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/parse/AyaParsing.java
base/src/main/java/org/aya/core/Matching.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/java/org/aya/core/DistillerTest.java
base/src/test/java/org/aya/tyck/TyckDeclTest.java
base/src/test/resources/failure/patterns/issues-archived/issue681.aya.txt
base/src/test/resources/failure/tyck/issues/issue697.aya.txt
base/src/test/resources/failure/tyck/issues2/issue34.aya.txt
cli/build.gradle.kts
cli/src/main/java/module-info.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
cli/src/main/java/org/aya/cli/utils/PicocliUtils.java
cli/src/test/java/org/aya/cli/ImGuiTrace.java
lsp/build.gradle.kts
lsp/src/main/java/org/aya/lsp/utils/LspArgs.java

Fix #147: see updated tests
Fix #154: dunno what to say, it's trivial

Many improvements to the pretty printer

---

base/src/main/java/org/aya/concrete/resolve/context/BindContext.java
base/src/main/java/org/aya/concrete/resolve/context/Context.java
base/src/main/java/org/aya/concrete/resolve/context/EmptyContext.java
base/src/main/java/org/aya/concrete/resolve/context/ModuleContext.java
base/src/main/java/org/aya/core/Matching.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/def/UserDef.java
base/src/main/java/org/aya/core/ops/Eta.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/term/ErrorTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/Substituter.java
base/src/main/java/org/aya/tyck/LocalCtx.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/resources/failure/patterns/issues/issue281.aya.txt
base/src/test/resources/success/issues/pull313.aya
pretty/src/main/java/org/aya/pretty/doc/Doc.java

Fix #162: add lossy comparison (`compareApprox`) in `compareUntyped`
Fix #163: fix SOE by changing the logic
Feature: add fuel to coverage checker

More bug fixes 

---

.github/README.md
build.gradle.kts
gradle/upload-maven.cmd
gradle/wrapper/gradle-wrapper.properties

Update readme and gradle

---

api/src/main/java/org/aya/api/concrete/ConcretePat.java
api/src/main/java/org/aya/api/util/Arg.java
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/desugar/BinExprParser.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/concrete/parse/AyaProducer.java
base/src/main/java/org/aya/concrete/resolve/visitor/PatResolver.java
base/src/main/java/org/aya/concrete/visitor/ExprConsumer.java
base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
base/src/main/java/org/aya/concrete/visitor/StmtConsumer.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/LicitProblem.java
base/src/test/java/org/aya/concrete/ParseTest.java
lsp/src/main/java/org/aya/lsp/actions/GotoDefinition.java
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
tools/src/main/java/org/aya/util/binop/BinOpParser.java

Follow up #178: improved the generalization of `BinOpParser` so it can be used in patterns more easily

Some preparation for binary patterns

---

api/src/main/java/org/aya/api/util/Arg.java
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/desugar/BinExprParser.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
tools/src/main/java/org/aya/util/binop/BinOpParser.java

Addresses https://github.com/aya-prover/aya-dev/pull/179#pullrequestreview-805425992, some last step refactoring
bors d=imkiva

Last-minute refactoring before pattern binop parser

---

base/src/main/java/org/aya/core/term/ElimTerm.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/resources/success/issues2/issue152.aya

Fix field pretty print

---

base/src/main/java/module-info.java
base/src/main/java/org/aya/concrete/parse/AyaProducer.java
base/src/main/java/org/aya/concrete/parse/ReporterErrorListener.java
base/src/main/java/org/aya/concrete/parse/error/BadCounterexampleWarn.java
base/src/main/java/org/aya/concrete/parse/error/BadModifierWarn.java
base/src/main/java/org/aya/concrete/parse/error/ParseError.java
base/src/main/java/org/aya/concrete/parse/error/PrimDependencyError.java
base/src/main/java/org/aya/concrete/parse/error/RedefinitionError.java
base/src/main/java/org/aya/concrete/parse/error/UnknownPrimError.java
base/src/main/java/org/aya/core/def/FnDef.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/visitor/Unfolder.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/generic/Modifier.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/resources/failure/syntax/issue165.aya.txt
buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4

Make `opaque` and `inline` keywords actually useful

---

base/src/main/java/org/aya/concrete/remark/CodeAttrProcessor.java
base/src/main/java/org/aya/concrete/remark/CodeOptions.java
base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/main/java/org/aya/concrete/remark/Remark.java
base/src/test/java/org/aya/experiments/CommonMark.java
base/src/test/resources/literate/standard-test.txt
base/src/test/resources/literate/test.aya
tools/src/main/java/org/aya/util/StringUtil.java

Yay!
Related to #21
See https://github.com/aya-prover/aya-dev/blob/3d5526efe18d1b3bf9efea5dd9b8eeed37edc0bc/base/src/test/resources/literate/test.aya
bors merge

Improve literate code options

---

.github/workflows/nightly-build.yml
base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/desugar/BinPatternParser.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/pat/Conquer.java

Supersede `Pat.Visitor` with JEP 406

---

cli/src/test/java/org/aya/cli/JlineReplTest.java
cli/src/test/java/org/aya/cli/PlainReplTest.java

Try to improve coverage

---

gradle/deps.properties
note/early-changelog.md
note/glossary.md
note/index-unification.md

Release 0.13

---

base/src/main/java/org/aya/concrete/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/concrete/stmt/Generalize.java
base/src/main/java/org/aya/core/def/DataDef.java
base/src/main/java/org/aya/core/def/StructDef.java
base/src/main/java/org/aya/core/def/UserDef.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/generic/ref/GeneralizedVar.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/order/SCCTycker.java
base/src/test/resources/failure/struct/universe.aya
base/src/test/resources/failure/struct/universe.aya.txt

As title. A step towards interleaved mutual recursion

Make `visitField` independent of the struct tycking

---

api/src/main/java/org/aya/api/concrete/ConcreteDecl.java
api/src/main/java/org/aya/api/concrete/ConcreteExpr.java
api/src/main/java/org/aya/api/concrete/ConcretePat.java
base/src/main/java/module-info.java
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/main/java/org/aya/concrete/remark/Remark.java
base/src/main/java/org/aya/concrete/resolve/ResolveInfo.java
base/src/main/java/org/aya/concrete/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/concrete/stmt/QualifiedID.java
base/src/main/java/org/aya/concrete/stmt/Signatured.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/tyck/LocalCtx.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/CircularSignatureError.java
base/src/main/java/org/aya/tyck/order/IncrementalTycker.java
base/src/main/java/org/aya/tyck/order/SCCTycker.java
base/src/main/java/org/aya/tyck/order/SigRefFinder.java
base/src/main/java/org/aya/tyck/order/TyckUnit.java
tools/src/main/java/org/aya/util/binop/BinOpParser.java
tools/src/main/java/org/aya/util/error/SourceNode.java

Introduce `TyckUnit`

---

base/src/main/java/org/aya/concrete/stmt/Signatured.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java

Address comments https://github.com/aya-prover/aya-dev/pull/217#pullrequestreview-812405838
bors r+

Minor bug fixes

---

base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/core/visitor/TermFixpoint.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/resources/failure/tyck/issues2/issue34.aya.txt
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/library/LibrarySource.java

Cherry pick from library system bug fix PR

---

base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/visitor/Unfolder.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/tyck/issues2/issue34.aya.txt

Error messages and unfold

---

api/src/main/java/org/aya/api/util/InternalException.java
base/src/main/java/org/aya/concrete/parse/AyaParsing.java
base/src/main/java/org/aya/concrete/parse/AyaProducer.java
base/src/main/java/org/aya/concrete/remark/Remark.java
base/src/main/java/org/aya/concrete/resolve/context/Context.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/concrete/stmt/Command.java
base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/concrete/stmt/Generalize.java
base/src/main/java/org/aya/concrete/stmt/Sample.java
base/src/main/java/org/aya/concrete/stmt/Signatured.java
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/core/serde/SerPat.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/tyck/order/TyckUnit.java
base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/java/org/aya/core/SuedeTest.java
base/src/test/java/org/aya/tyck/TyckDeclTest.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
cli/src/main/java/org/aya/cli/utils/AyaCompiler.java
tools/src/main/java/org/aya/util/error/SourceFile.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Try to fix some obvious bugs of the library system

---

api/src/main/java/org/aya/api/error/CollectingReporter.java
api/src/main/java/org/aya/api/error/DelayedReporter.java
api/src/main/java/org/aya/api/error/Problem.java
base/src/main/java/org/aya/tyck/error/HoleProblem.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/test/java/org/aya/test/LibraryTest.java
base/src/test/java/org/aya/test/TestRunner.java
base/src/test/java/org/aya/test/ThrowingReporter.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/repl/Repl.java
cli/src/main/java/org/aya/cli/single/CliReporter.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
tools/src/main/java/org/aya/util/FileUtil.java

Improve cli output, add `--verbosity` flag

---

base/src/test/java/org/aya/test/LibraryTest.java

https://github.com/aya-prover/aya-dev/pull/229#discussion_r754967702

Run library test for 3 times as said in the review

---

base/src/main/java/org/aya/concrete/resolve/ModuleCallback.java
base/src/main/java/org/aya/concrete/resolve/ResolveInfo.java
base/src/main/java/org/aya/concrete/resolve/module/CachedModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/module/EmptyModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/module/FileModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/module/ModuleListLoader.java
base/src/main/java/org/aya/concrete/resolve/module/ModuleLoader.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/test/java/org/aya/tyck/TyckDeclTest.java
base/src/test/resources/success/common/src/Arith/Nat.aya
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/common/src/Paths.aya
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
tools/src/main/java/org/aya/util/FileUtil.java

Attempt to simplify the interfaces

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/ops/TermToPat.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LocalCtx.java
base/src/main/java/org/aya/tyck/trace/Trace.java
lsp/src/main/java/org/aya/lsp/actions/ComputeTerm.java

I'm preparing for something big

Minor refactoring

---

base/src/main/java/org/aya/core/ops/Eta.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/LocalCtx.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/java/org/aya/core/EtaTest.java

Rely on `LocalCtx`

---

base/src/main/java/org/aya/concrete/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/concrete/resolve/visitor/StmtShallowResolver.java

This commit makes resolving operators in one place (`StmtShallowResolver#resolveOpInfo`) together with `BinOpCollector`
bors merge

Cherry pick refactoring changes from mixfix

---

base/src/main/java/org/aya/core/Matching.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/visitor/Substituter.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/java/org/aya/tyck/PatCCTest.java

Logical decomposition of the lhs and rhs tycking of pattern matching clauses

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/MCT.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/java/org/aya/tyck/PatCCTest.java

Reference: http://personal.psu.edu/yqz5714/wits22-draft-1.pdf
One more step towards #243

Generate multi-case trees

---

base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/MCT.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/patterns/fm-dom.aya.txt

Put uninlined code to pattern classifier

---

lsp/src/main/java/org/aya/lsp/server/AyaServer.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

Register library if it's not yet initialized

---

base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/error/NotYetTyckedError.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java

Random changes

---

base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/test/resources/failure/patterns/issues2/issue250.aya
base/src/test/resources/failure/patterns/issues2/issue250.aya.txt
base/src/test/resources/success/src/Issues/250.aya

Fixes #250 
https://www.bilibili.com/video/BV1V34y1R7TZ
bors r+

Concrete data stores core constructors

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/resources/success/common/src/Arith/Nat.aya
base/src/test/resources/success/common/src/Data/List.aya
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/src/NatMonoid.aya

Improve `common`. Probably I'm gonna add more code in this PR stay tuned

Fix prim levels

---

base/build.gradle.kts
gradle/deps.properties

Use commonmark packaged by ourselves

---

api/src/main/java/org/aya/api/error/BufferReporter.java
api/src/main/java/org/aya/api/error/CollectingReporter.java
api/src/main/java/org/aya/api/error/CountingReporter.java
api/src/main/java/org/aya/api/error/IgnoringReporter.java
api/src/main/java/org/aya/api/error/Problem.java
api/src/main/java/org/aya/api/error/Reporter.java
base/src/test/java/org/aya/test/StreamReporter.java
base/src/test/java/org/aya/test/TestRunner.java
base/src/test/java/org/aya/test/ThrowingReporter.java
cli/src/main/java/module-info.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/single/CliReporter.java
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
pretty/src/main/java/org/aya/pretty/backend/string/custom/UnixTermStyle.java
pretty/src/main/java/org/aya/pretty/backend/string/style/UnixTermStylist.java

- close #223
- make `CountingReporter` an interface
-  make some output styled

Enhance reporters

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/common/src/Data/Vec.aya
lsp/src/main/java/org/aya/lsp/actions/GotoDefinition.java

bors merge this which fixes #257

Insert metas on elimination

---

base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/common/src/Homotopy.aya
note/unfiled.md

Some are asked by @xieyuheng.
bors merge this trivial PR pwease

Fix bugs, add some lib code

---

.github/README.md
gradle/deps.properties
note/early-changelog.md

Release 0.14

---

cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/main/java/org/aya/cli/repl/ReplCommands.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli/src/test/java/org/aya/cli/JlineReplTest.java
cli/src/test/java/org/aya/cli/PlainReplTest.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

This PR makes REPL load libraries by traversing all the sources of a library (including its dependencies) and manually importing their exported definitions (maybe all definitions for debugging purpose?) to the REPLContext.
close #226

Library in REPL

---

api/src/main/java/org/aya/api/core/CoreTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/VarConsumer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/resources/success/common/src/Arith/Nat.aya
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/common/src/Paths.aya

Delay equations on flex-flex cases

---

base/src/main/java/org/aya/concrete/GenericAyaParser.java
base/src/main/java/org/aya/tyck/TyckState.java

bors merge because I forgot to include this in #265

Unimportant PR

---

base/src/main/java/org/aya/core/pat/PatMatcher.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/Normalizer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/resources/success/common/src/Data/List.aya

Relevant: #81
Fixes: #271
Come color up my life~
bors r+

Add more necessary normalizations

---

base/src/test/resources/failure/patterns/issues/issue363.aya
base/src/test/resources/failure/patterns/issues/issue363.aya.txt
base/src/test/resources/success/src/ProtoIssues/313.aya
buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
buildSrc/src/main/groovy/org/aya/gradle/GenerateLexerTokenTask.groovy
cli/src/main/java/org/aya/cli/parse/AyaProducer.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/main/java/org/aya/cli/repl/ReplCommands.java

Fix #278 
Fix #273 
bors merge this now

Fix two issues

---

base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/Substituter.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/resources/failure/holes/pattern-confluence.aya.txt
base/src/test/resources/failure/holes/ulf-hole-illtype.aya.txt
base/src/test/resources/failure/struct/field-type-mismatch.aya.txt
base/src/test/resources/failure/syntax/issue293-emoji32.aya.txt
base/src/test/resources/failure/syntax/issue293-emoji64.aya.txt
base/src/test/resources/failure/syntax/issue293.aya.txt
base/src/test/resources/failure/syntax/literate-ill-typed.aya.txt
base/src/test/resources/failure/tyck/issues/issue292.aya.txt
base/src/test/resources/failure/tyck/issues/issue300.aya.txt
base/src/test/resources/failure/tyck/issues2/issue34.aya.txt
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/common/src/Paths.aya
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

More precise unification error report

---

api/src/main/java/org/aya/api/core/CorePat.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/serde/SerPat.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java

bors merge this work inspired from #281, related to #242

Delete `Pat::type`, `Tuple::type`, `Prim::type`, `Absurd::type`

---

base/src/main/java/org/aya/tyck/pat/PatternProblem.java
base/src/test/resources/failure/patterns/selection-failure.aya.txt
base/src/test/resources/success/common/src/Arith/Nat/Order.aya
base/src/test/resources/success/common/src/Data/Empty.aya

Anybody wanna prove more lemmata?

Prove some simple facts about <

---

cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/source/DiskLibraryOwner.java
cli/src/main/java/org/aya/cli/library/source/LibraryOwner.java
cli/src/main/java/org/aya/cli/library/source/MutableLibraryOwner.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
lsp/src/main/java/org/aya/lsp/library/WsLibrary.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

Handle file create and delete event in LSP

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/generic/ParamLike.java

Something I've done in #287 but it doesn't feel nice enough. I'm refactoring both the impl and the code design
bors d=imkiva

Improve pretty printer

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/AyaBinOpSet.java
base/src/main/java/org/aya/concrete/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/concrete/visitor/ExprConsumer.java
base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
base/src/main/java/org/aya/concrete/visitor/StmtConsumer.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/IntroTerm.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/generic/ParamLike.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/test/resources/failure/patterns/issues/issue681.aya.txt
build.gradle.kts
cli/src/main/java/module-info.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
lsp/src/main/java/org/aya/lsp/actions/ComputeSignature.java
lsp/src/main/java/org/aya/lsp/actions/FindReferences.java
lsp/src/main/java/org/aya/lsp/actions/GotoDefinition.java
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/server/AyaServer.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
lsp/src/main/java/org/aya/lsp/utils/Log.java
lsp/src/main/java/org/aya/lsp/utils/LspRange.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
tools/src/main/java/org/aya/util/MutableGraph.java

- Highlight and Goto Def. using core terms to support serialized dependencies
- Hover mouse on a term to show its type
- Find references

Enhance LSP

---

cli/src/main/java/module-info.java
lsp/build.gradle.kts

bors merge this PR which closes #295

Fix jlink relevant issues

---

build.gradle.kts
buildSrc/src/main/groovy/org/aya/gradle/GenerateLexerTokenTask.groovy
lsp/build.gradle.kts

Fix some build issues

---

lsp/src/main/java/org/aya/lsp/utils/Resolver.java

Fix a simple problem

---

lsp/src/main/java/org/aya/lsp/actions/ComputeSignature.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

Fix lots of bugs

---

base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/visitor/Unfolder.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/test/resources/success/common/src/Cubical.aya

Fix #304 
Fix #307 
Add some definitions in the lib

Define square

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/error/OperatorProblem.java
base/src/main/java/org/aya/core/sort/Sort.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/generic/Level.java

Use more pm

---

base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java

Use even more pm

---

api/src/main/java/org/aya/api/ref/DefVar.java
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/BinExprParser.java
base/src/main/java/org/aya/concrete/desugar/BinPatternParser.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/concrete/stmt/Command.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/resolve/ResolveInfo.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/test/java/org/aya/concrete/DesugarTest.java
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/common/src/Primitives.aya
base/src/test/resources/success/src/Invol.aya
base/src/test/resources/success/src/Issues/289.aya
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

fix #289 
Some code looks ugly and will be addressed after removing `api` module.

Renaming in open command

---

base/src/main/java/org/aya/concrete/stmt/Signatured.java
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

Minor refactorings, improve `Signatured::toString`

---

base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/test/resources/success/src/Issues/337.aya

RefTerms in the header should depend on the whole referred body (#337)

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
cli/src/main/java/org/aya/cli/parse/AyaProducer.java
lsp/build.gradle.kts
lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

Make LSP work again!

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/visitor/ExprConsumer.java
base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/success/src/Issues/339.aya
base/src/test/resources/success/src/Refparo/Model.aya

Fix #339. I think we had this long time ago, but I forgot to reimplement this after a huge refactoring. Thanks @refparo for discovering this and reminding me to do it!

Substitute patterns for variables in telescope

---

base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/success/common/src/Data/Unit.aya
base/src/test/resources/success/src/Issues/339.aya
base/src/test/resources/success/src/Issues/346.aya
tools/src/main/java/org/aya/util/error/SourcePos.java

Use better source pos

---

base/src/main/java/org/aya/core/visitor/Substituter.java
base/src/main/java/org/aya/core/visitor/Unfolder.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/src/Issues/336.aya

Also lift struct fields

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/LevelError.java
base/src/test/resources/failure/levels/refparo5.aya.txt
base/src/test/resources/failure/levels/too-high.aya.txt
base/src/test/resources/failure/tyck/issues/issue697.aya.txt

Ensure pi body normalized

---

base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/patterns/issues2/issue352.aya
base/src/test/resources/failure/patterns/issues2/issue352.aya.txt
note/early-changelog.md

Fix crash on no patterns

---

base/src/main/java/org/aya/core/Meta.java
base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/visitor/TermConsumer.java
base/src/main/java/org/aya/core/visitor/TermFixpoint.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/unify/DefEq.java

Lift a meta and unlift the solution

---

base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/ErrorTerm.java
gradle/deps.properties
note/early-changelog.md

Bump version to 0.16, update javadoc

---

base/src/test/resources/failure/syntax/issue164.aya.txt
base/src/test/resources/failure/syntax/issue165.aya.txt
buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java

Fix grammar

---

base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/TermOps.java
base/src/main/java/org/aya/core/visitor/TermView.java

I've compared the new approach with the old one and there are two comments labeled `CHECK` that highlight the differences. May need to double check those changes are valid.

REFACTOR: Implement full normalization with `TermView`.

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/NoRuleError.java
base/src/test/resources/failure/operator/ambiguous.aya
base/src/test/resources/failure/operator/ambiguous.aya.txt
base/src/test/resources/failure/operator/no-assoc.aya
base/src/test/resources/failure/operator/no-assoc.aya.txt

This fixes issue #377 and #378.

Fix "no rule" reporting and ErrorExpr inference

---

base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatMatcher.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/generic/util/InternalException.java
base/src/main/java/org/aya/resolve/module/EmptyModuleLoader.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/main/java/org/aya/terck/CallMatrix.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/error/CircularSignatureError.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/json/LibraryDependencyData.java
cli/src/main/java/org/aya/cli/parse/AyaProducer.java
lsp/src/main/java/org/aya/lsp/utils/Log.java

Throws `InternalException` instead of `IllegalxxxException`

---

base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/NobodyError.java
base/src/main/java/org/aya/tyck/unify/DefEq.java
base/src/test/resources/failure/patterns/issues2/issue384.aya
base/src/test/resources/failure/patterns/issues2/issue384.aya.txt
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java

Cherry pick

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java

Rewrite ExprResolver with pattern matching

Rewrite ExprResolver with pattern matching

---

.github/workflows/nightly-build.yml

Upstream change: https://github.com/weareyipyip/walking-tag-action/pull/2

Fix nightly build

---

.github/workflows/move-tag.sh
.github/workflows/nightly-build.yml

Fixes what should be fixed in #389

Get rid of shitty upstream and really fix nightly build

---

.editorconfig
.github/workflows/commit-check.yml
.github/workflows/gradle-check.yml
.github/workflows/nightly-build.yml

Build native image in CI

---

cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/repl/ReplContext.java
cli/src/main/java/org/aya/cli/utils/RepoLike.java
cli/src/test/java/org/aya/cli/ReplCompilerTest.java

REPL enhancement

---

base/src/main/java/module-info.java
base/src/main/java/org/aya/core/repr/AyaShape.java
base/src/main/java/org/aya/core/repr/CodeShape.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/test/java/org/aya/repr/ShapeMatcherTest.java

Code Shape Matcher

---

base/src/main/java/org/aya/tyck/error/NotAnIntervalError.java

Add `NotAnIntervalError`

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/PrimTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/DefEq.java

Make `FormTerm.Interval` and `PrimTerm.End` singleton

---

base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/test/resources/success/src/Implicits.aya
buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
gradle/deps.properties
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java

Improve pretty and syntax for named applications

---

.github/workflows/nightly-build.yml
base/reflect-config.txt
build.gradle.kts
buildSrc/src/main/java/org/aya/gradle/StripPreview.java

This is done by rewriting the major version to 61.

Try to fix nightly build with Java 18

---

build.gradle.kts
buildSrc/src/main/java/org/aya/gradle/StripPreview.java

BUILD: shrink strip preview messages

---

base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/visitor/TermOps.java
base/src/test/java/org/aya/core/NormalizeTest.java

This should supersede #411 
/cc @imkiva @lunalunaa

Normalizer should subst before normalizing

---

base/src/main/java/module-info.java
build.gradle.kts
cli/src/main/java/module-info.java
lsp/build.gradle.kts
lsp/src/main/java/module-info.java
lsp/src/main/java/org/aya/lsp/server/AyaServer.java
parser/module-info.java
pretty/src/main/java/module-info.java
tools-repl/src/main/java/module-info.java
tools/src/main/java/module-info.java

JPMS and build script improvement

---

lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/models/HighlightResult.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
lsp/src/main/java/org/aya/lsp/utils/ForIDEA.java

Slightly refactor for intellij-aya

---

.github/workflows/gradle-check.yml
.github/workflows/nightly-build.yml
build.gradle.kts
gradle/deps.properties
gradle/wrapper/gradle-wrapper.properties

Maybe we should let Actions publishing snapshot automatically

Rework publishing and versioning

---

base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya.txt

Put bind patterns in separate leaf nodes

---

base/build.gradle.kts
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/test/java/org/aya/test/LibraryTest.java
base/src/test/resources/failure/counterexamples/not-counterexample.aya.txt
cli/src/main/java/org/aya/cli/library/ImportResolver.java
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/incremental/CompilerAdvisor.java
cli/src/main/java/org/aya/cli/library/incremental/DelegateCompilerAdvisor.java
cli/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
cli/src/main/java/org/aya/cli/library/incremental/InMemoryCompilerAdvisor.java
cli/src/main/java/org/aya/cli/library/source/LibrarySource.java
cli/src/main/java/org/aya/cli/parse/AyaProducer.java
lsp/src/main/java/org/aya/lsp/server/AyaLanguageClient.java
lsp/src/main/java/org/aya/lsp/server/AyaServer.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
lsp/src/main/java/org/aya/lsp/utils/Log.java
lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java
lsp/src/test/java/org/aya/lsp/tester/LspTestCompilerAdvisor.java
lsp/src/test/resources/lsp-test-lib/src/HelloWorld.aya
lsp/src/test/resources/lsp-test-lib/src/PathPrims.aya

This PR also improved LSP reload performance by reducing expensive graph operations and needless LSP protocol calls.

Fix primitive reload and polish some error messages

---

build.gradle.kts
gradle/deps.properties
note/early-changelog.md

Release 0.19 and bump version to 0.20-SNAPSHOT

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/stmt/Generalize.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/EndoFunctor.java
base/src/main/java/org/aya/generic/ParamLike.java
base/src/test/resources/failure/syntax/issue165.aya.txt
buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
cli/src/main/java/org/aya/cli/parse/AyaProducer.java
note/early-changelog.md

Remove planned generalized pattern synonym

---

cli/build.gradle.kts
lsp/aya-lsp.bat
lsp/aya-lsp.sh
lsp/aya.bat
lsp/aya.sh
lsp/build.gradle.kts

Address module renames in run scripts

---

base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/term/ElimTerm.java
base/src/main/java/org/aya/core/visitor/EndoFunctor.java
base/src/main/java/org/aya/core/visitor/Expander.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/unify/DefEq.java

ajkncjskdvuierbuindnjkdsncjdskncjkdsnjk

Cherry pick from @tsao-chi branch

---

lsp/src/main/java/org/aya/lsp/server/AyaLanguageClient.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java
lsp/src/main/java/org/aya/lsp/utils/XY.java
tools/src/main/java/org/aya/util/error/SourcePos.java

+ Clicking the LHS of an identifier now also jumps to its definition
+ Fix #458 
bors r+

Improve LSP

---

note/early-changelog.md

pull @tsao-chi 's branch to main

RELEASE: updated changelog for 0.19

---

base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/test/resources/success/src/ImportOpPrecedence.aya

fix https://github.com/aya-prover/aya-dev/issues/450

RESOLVE: fix specifying precedence between imported operators

---

.gitignore
base/src/main/java/org/aya/generic/Constants.java
base/src/main/java/org/aya/generic/util/AyaFiles.java
base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
base/src/test/java/org/aya/test/TestRunner.java
cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
cli/src/main/java/org/aya/cli/library/source/DiskLibraryOwner.java
cli/src/main/java/org/aya/cli/library/source/LibrarySource.java
lsp/src/main/java/org/aya/lsp/server/AyaService.java

Prepare for literate aya

---

base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/java/org/aya/core/DistillerTest.java

fix https://github.com/aya-prover/aya-dev/issues/472

PRETTY: fix partially applied binop

---

base/src/main/java/org/aya/tyck/ExprTycker.java

This is a part of https://github.com/aya-prover/aya-dev/issues/448

TYCK: add inheritUniv() api

---

gradle/deps.properties
gradle/upload-maven.cmd
note/early-changelog.md

RELEASE: 0.20 and bump version to 0.21-SNAPSHOT

---

.github/README.md
base/src/main/java/org/aya/terck/Behavior.java
base/src/main/java/org/aya/terck/CallGraph.java
base/src/main/java/org/aya/terck/CallMatrix.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/terck/Relation.java
base/src/main/java/org/aya/terck/error/NonTerminating.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/test/java/org/aya/terck/RelationTest.java
base/src/test/resources/failure/terck/issue471.aya
base/src/test/resources/failure/terck/issue471.aya.txt
base/src/test/resources/success/src/FoetusLimitation.aya

This is highly based on the idea from:
- Amir M. Ben-Amram, & Chin Soon Lee (2009). Ranking Functions for Size-Change Termination II. Log. Methods Comput. Sci., 5(2).
and implementation details from:
- https://github.com/agda/agda/blob/master/src/full/Agda/Termination/TermCheck.hs
Really fixes #471 and supersedes #481

Consider size-change in termination checker

---

bors.toml
gradle/deps.properties

bors r+
/cc @lunalunaa the function you need is `CofThy.isOne`

Update bors message, upgrade guest

---

.github/workflows/commit-check.yml

Do not run commit-check on main

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/EndoFunctor.java
base/src/main/java/org/aya/core/visitor/Expander.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/java/org/aya/cubical/PartialTest.java

Some changes

---

base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/success/src/Issues/495.aya

Fix #495
bors r+
Thank you @HoshinoTented

Inline with context

---

base/src/main/java/org/aya/concrete/visitor/ExprView.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/java/org/aya/core/DistillerTest.java
base/src/test/resources/success/src/Issues/506.aya

Fix two bugs

---

base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/unify/DefEq.java

Fix many bugs in partial and path type support. Coauthored by @imkiva.

Cherry pick 2 from `coe-subst` branch

---

cli/src/main/java/module-info.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/plct/GsonClasses.java
cli/src/main/java/org/aya/cli/plct/PLCTReport.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
note/early-changelog.md

Changelog & plct report generator

---

cli/src/main/java/module-info.java
gradle/deps.properties

Add `Traversable::anyMatchWith`, `Traversable::allMatchWith` and `Traversable::noneMatchWith`

KALA: upgrade to 0.50.0

---

base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/test/java/org/aya/core/DistillerTest.java

Attempt to fix #514 and fix #515.

Distiller fix

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/tyck/Tycker.java
base/src/main/java/org/aya/tyck/error/CubicalError.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/main/java/org/aya/tyck/unify/Unifier.java

Also split `Unifier` into a class for bidirectional conversion checking and a class for meta solving.
bors merge

Rename `DefEq` to `Unifier`

---

.github/workflows/nightly-build.yml
build.gradle.kts
parser/build.gradle.kts

Fix nightly build for Java 19

---

.github/workflows/nightly-build.yml
build.gradle.kts

ci: really fix for Java 19

---

base/src/main/java/org/aya/concrete/visitor/PatternTraversal.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/success/common/src/Paths.aya
lsp/src/test/java/org/aya/lsp/LspTest.java
lsp/src/test/java/org/aya/lsp/tester/LspTestCompilerAdvisor.java
lsp/src/test/resources/lsp-test-lib/src/Vec.aya

Improve inlay-hint info

---

cli/build.gradle.kts
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
tools/src/main/java/org/aya/util/reporter/CollectingReporter.java
tools/src/main/java/org/aya/util/reporter/CountingReporter.java
tools/src/main/java/org/aya/util/reporter/Reporter.java

Support explicitly raising errors in reporter

---

build.gradle.kts
lsp/src/main/java/org/aya/lsp/server/AyaLanguageClient.java
lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java

Refactor `AyaLanguageClient` for IJ plugin

---

base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/test/java/org/aya/concrete/DesugarTest.java
base/src/test/resources/success/common/src/Data/List.aya
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
cli/src/test/java/org/aya/cli/JlineReplTest.java
tools-repl/src/main/java/org/aya/repl/gk/ReplParser.java

Try to save coverage, recover do/idiom tests

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/concrete/visitor/ExprView.java
base/src/main/java/org/aya/concrete/visitor/StmtOps.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/generic/SortKind.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java

As title. More refactorings are welcomed, but IntelliJ currently don't understand these code

Use some Java 19 features

---

base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/test/java/org/aya/concrete/ParseTest.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
cli/src/test/java/org/aya/cli/ReplParserTest.java
cli/src/test/java/org/aya/cli/WidthPreviewToy.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java

@HoshinoTented's branch

---

base/src/main/java/org/aya/core/term/CallTerm.java
base/src/main/java/org/aya/core/term/ElimTerm.java
base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/DeltaExpander.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/trace/MarkdownTrace.java
base/src/main/java/org/aya/tyck/trace/MdUnicodeTrace.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/java/org/aya/tyck/TracingTest.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/test/java/org/aya/cli/ImGuiTrace.java
lsp/aya.bat
lsp/build.gradle.kts

This PR:
+ Improves `MdUnicodeTrace` as also an ASCII trace
+ Improved `applyDimsTo`
+ Improved build script with more inputs

Cherry pick from an ongoing feature branch

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/common/src/Arith/Nat.aya
base/src/test/resources/success/common/src/Arith/Nat/More.aya
base/src/test/resources/success/common/src/Paths.aya
build.gradle.kts

bors r+
All improvements are minor.

More minor improvements

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/test/resources/success/src/Idiom.aya
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Desugar empty idiom brackets with `empty`

---

base/src/main/java/org/aya/core/visitor/DeltaExpander.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/test/resources/failure/tyck/nonsigma-tup.aya.txt
base/src/test/resources/success/src/Refparo/Model.aya

bors r+
Fixed some lifting problems, closes #521

Lifting order

---

base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/failure/patterns/issues2/issue578.aya
base/src/test/resources/failure/patterns/issues2/issue578.aya.txt

Do not stop literal classification that early

---

tools/src/main/java/org/aya/util/tyck/MCT.java

mct: fix slow code by @imkiva

---

base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatMatcher.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/LitTerm.java
base/src/main/java/org/aya/generic/Shaped.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java

But instead use normalization
bors d=imkiva

Fix #528 by not using unification

---

pretty/src/main/java/module-info.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/style/AyaColorScheme.java
pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java

https://github.com/aya-prover/aya-dev/pull/581#issuecomment-1279626774

Make PrettyPrinter Alive

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java

Some Java 19 shit

---

base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/UnifyError.java

I think what we're missing now is `coe` reductions, I guess (I hope).
bors r+

Some improvements generated in `andras` branch

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/patterns/issues2/issue597.aya
base/src/test/resources/failure/patterns/issues2/issue597.aya.txt
base/src/test/resources/success/src/Issues/597.aya

Fix: Issue 597

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/PrimTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/main/java/org/aya/tyck/unify/Unifier.java
base/src/test/resources/success/src/CubicalBasics.aya

This pull request implements the computation rule for `coe` on a Pi type.

Computation for `coe`

---

base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/resolve/ResolveInfo.java
base/src/test/resources/success/common/src/Paths.aya

Test for this PR has been applied to `Paths.aya`

respect renamed operator in serialized bind

---

base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/main/java/org/aya/tyck/unify/Unifier.java

Overhaul the `Sub` system of unification

---

base/src/main/java/org/aya/core/term/FormTerm.java
base/src/main/java/org/aya/terck/CallGraph.java
base/src/main/java/org/aya/tyck/env/MapLocalCtx.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/failure/patterns/issues2/issue437.aya
base/src/test/resources/failure/patterns/issues2/issue437.aya.txt
gradle/deps.properties

fix regression of #437 in #579

---

base/reflect-config.txt
cli/src/main/java/org/aya/cli/library/source/MutableLibraryOwner.java
gradle/wrapper/gradle-wrapper.properties
lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
parser/build.gradle.kts

Add `SerTerm.ShapedList` to `reflect-config.txt`, upgrade gradle

Many build improvements

---

gradle/wrapper/gradle-wrapper.properties

TIL https://services.gradle.org/distributions/ which shows m1 is like a month ago. So 
rc1 let's go!
bors r+

Upgrade (again, sorry!)

---

base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/test/resources/success/src/CubicalBasics.aya

This implements computation rule of coe for binary sigma types with a test.

Computation rule of coe for sigma type

---

LICENSE
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/test/java/org/aya/concrete/ParseTest.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
lsp/src/main/java/org/aya/lsp/actions/ComputeTerm.java
lsp/src/main/java/org/aya/lsp/models/ComputeTermResult.java
lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java

Random changes, fix simple lsp bug

---

base/src/main/java/org/aya/distill/Codifier.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/main/java/org/aya/cli/repl/ReplCommands.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/repl/ReplConfig.java
cli/src/test/java/org/aya/cli/CodifierTest.java
cli/src/test/java/org/aya/cli/PlainReplTest.java
cli/src/test/java/org/aya/cli/ReplTestBase.java

Codifier: a new tool for writing helper functions internally

---

base/src/main/java/org/aya/core/pat/PatMatcher.java

Fixed: normalizing too early when the pat is binding.

Don't normalize too early

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/term/CoeTerm.java
base/src/main/java/org/aya/core/term/PartialTyTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/AyaRestrSimplifier.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/Subst.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/src/CubicalBasics.aya
gradle/deps.properties

/cc @lunalunaa 
bors r+
All changes are considered trivial refactoring so instant merge.
bors r+

Define `coeSigma4` and `coeSigma5`, upgrade guest with a smol optimization

---

base/src/test/java/org/aya/concrete/ParseTest.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/grammar/AyaPsiLexer.flex

Allow connected ↑

---

base/src/main/java/org/aya/core/term/SigmaTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/src/CubicalBasics.aya

/cc @lunalunaa 
Also fix lipu bug

Sigma transport

---

base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/core/term/SortTerm.java
base/src/main/java/org/aya/generic/SortKind.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java

bors merge xsuaixsiaxhjqheudbcjkfwuigyhbtvfjdcbhijkl

NXJASbhjasbxjhsbxhjasbxhjasbxjas

---

gradle/deps.properties
tools/src/main/java/org/aya/util/Version.java

Fix some LSP bugs

---

base/src/test/java/org/aya/concrete/ParseTest.java
base/src/test/java/org/aya/literate/LiterateTest.java
cli/src/main/java/org/aya/cli/Main.java
cli/src/main/java/org/aya/cli/library/incremental/CompilerAdvisor.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
cli/src/main/java/org/aya/cli/parse/AyaParserImpl.java
cli/src/main/java/org/aya/cli/repl/ReplCommands.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/main/java/org/aya/cli/repl/ReplConfig.java
cli/src/main/java/org/aya/cli/single/CompilerFlags.java
cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
cli/src/test/java/org/aya/cli/RenderOptionsTest.java
cli/src/test/java/org/aya/cli/ReplParserTest.java
gradle/deps.properties
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
tools-repl/src/main/java/org/aya/repl/CommandManager.java
tools-repl/src/main/java/org/aya/repl/ReplCompleters.java

Add some cli options

---

base/src/main/java/org/aya/distill/BaseDistiller.java
build.gradle.kts
gradle/deps.properties
note/early-changelog.md

Release v0.23

---

base/src/main/java/org/aya/core/def/PrimDef.java
lsp/aya.bat
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java

Fix some bugs 

---

base/src/test/resources/success/src/Issues/663.aya

Use the meaningful test data

---

lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java

LSP: Search library root in dependencies

---

base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/test/resources/failure/scope/did-you-mean-disamb.aya
base/src/test/resources/failure/scope/did-you-mean-disamb.aya.txt
base/src/test/resources/failure/scope/did-you-mean.aya
base/src/test/resources/failure/scope/did-you-mean.aya.txt

Better `did you mean` messages

---

base/src/test/resources/failure/syntax/issue679.aya
base/src/test/resources/failure/syntax/issue679.aya.txt
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Parse private decl

---

base/src/main/java/org/aya/concrete/desugar/BinExprParser.java
base/src/main/java/org/aya/concrete/desugar/BinPatternParser.java
base/src/main/java/org/aya/concrete/error/OperatorError.java
base/src/test/resources/failure/operator/issue677.aya
base/src/test/resources/failure/operator/issue677.aya.txt
tools/src/main/java/org/aya/util/binop/BinOpParser.java

Report mising operand for unary sections

---

base/src/test/resources/success/common/src/Spaces/Segment.aya
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

/cc @imkiva 
We may want to improve the producer by this.

Try using `meta` rules

---

lsp/aya-lsp.bat
lsp/aya-lsp.sh
lsp/aya.bat
lsp/aya.sh
lsp/build.gradle.kts

Rename java to jaya

---

cli/src/main/java/org/aya/cli/render/RenderOptions.java
cli/src/main/java/org/aya/cli/repl/AyaRepl.java
cli/src/main/java/org/aya/cli/repl/ReplCommands.java
cli/src/main/java/org/aya/cli/repl/ReplConfig.java
cli/src/test/java/org/aya/cli/PlainReplTest.java
cli/src/test/java/org/aya/cli/RenderOptionsTest.java
tools-repl/src/main/java/org/aya/repl/CommandArg.java

fix #694
- Memorize `stylist` for each output target
- Strongly typed argument for `:color` and `:style`, as well as completions!

Kiva fixing something today

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/env/MapLocalCtx.java
base/src/main/java/org/aya/tyck/env/SeqLocalCtx.java

Cherry pick from 'no more duplicated vars'

---

base/src/test/resources/success/aya.json
base/src/test/resources/success/common/aya.json
base/src/test/resources/success/nonsense/aya.json
cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli/src/main/java/org/aya/cli/library/json/LibraryConfigData.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
cli/src/test/java/org/aya/cli/LibraryConfigParseTest.java
cli/src/test/java/org/aya/cli/ReplCompilerTest.java
lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
lsp/src/test/resources/lsp-test-lib/aya.json

New `group` library config and polish some messages

---

cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Interesting parser improvements

---

cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Slightly less code in parser

---

parser/src/main/grammar/AyaPsiParser.bnf

bnf: make `LetBind` a named element

---

base/src/test/resources/success/common/src/Data/List/Core.aya
base/src/test/resources/success/src/TestStd/Data/List/Test.aya

@ice1000 requested me to rewrite the `curry` in `Data::List::Core` with `let-expression`, so I do.

Leafover of Let Expr

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/syntax/issue164.aya.txt
base/src/test/resources/failure/syntax/let-expr2.aya
base/src/test/resources/failure/syntax/let-expr2.aya.txt
base/src/test/resources/failure/syntax/let-expr3.aya
base/src/test/resources/failure/syntax/let-expr3.aya.txt
base/src/test/resources/failure/syntax/literate-unresolved.aya.txt
base/src/test/resources/success/src/LetExpr.aya
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
pretty/src/main/java/org/aya/pretty/error/PrettyError.java
pretty/src/main/java/org/aya/pretty/error/Span.java

Fix SourcePos of Let

---

gradle/deps.properties
note/early-changelog.md

Release 0.24

---

base/src/test/resources/success/common/src/Arith/Nat/Core.aya
base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/common/src/Spaces/Torus/T2-HoTT.aya

Also define new T² type from HoTT book

Add `*-comm`, `*-assoc` in library candidate

---

base/src/main/java/org/aya/concrete/stmt/Decl.java
base/src/main/java/org/aya/concrete/stmt/TeleDecl.java
base/src/main/java/org/aya/concrete/visitor/StmtConsumer.java
base/src/main/java/org/aya/core/def/CtorDef.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/def/FieldDef.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/main/java/org/aya/core/term/Callable.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/order/SigRefFinder.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/actions/ComputeSignature.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

Remove ulift

---

base/src/main/java/org/aya/core/visitor/DeltaExpander.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/resources/failure/patterns/issues2/issue746.aya
base/src/test/resources/failure/patterns/issues2/issue746.aya.txt
base/src/test/resources/success/common/src/Spaces/Sphere/S1/Core.aya
base/src/test/resources/success/src/Issues/748.aya

+ Fix #746 
+ Fix #748 
bors r+

Fix many problems again

---

.github/README.md
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/term/MatchTerm.java
base/src/main/java/org/aya/core/term/SortTerm.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/test/java/org/aya/tyck/TracingTest.java
base/src/test/java/org/aya/tyck/TyckDeclTest.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
lsp/src/main/java/org/aya/lsp/actions/Folding.java
lsp/src/main/java/org/aya/lsp/actions/InlayHintMaker.java
lsp/src/main/java/org/aya/lsp/actions/ProjectSymbol.java
tools/src/main/java/org/aya/util/binop/OpDecl.java

Run IDE inspections

---

base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java
tools/src/main/java/org/aya/util/StringUtil.java

Also fold resolved binds

---

base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
lsp/src/main/java/org/aya/lsp/models/HighlightResult.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

You need to upgrade VSCode frontend too (wait a sec)

Support highlighting module names

---

base/build.gradle.kts
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/resources/literate/hoshino-said.aya.md
cli/src/main/java/org/aya/cli/literate/AyaMdParser.java
cli/src/main/java/org/aya/cli/single/SingleAyaFile.java
tools/src/main/java/org/aya/util/error/SourceFile.java

Fix some random bugs

---

cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java

Fix Highlighting of the Param of Lambdas

---

cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java

Escape backslash

---

base/src/main/java/org/aya/tyck/ExprTycker.java

FreezeHoles and check type in `doTy`

---

base/src/main/java/org/aya/tyck/ExprTycker.java

tyck: remove failSort

---

base/src/main/java/org/aya/tyck/ExprTycker.java

tyck(): cleanup ty()

---

base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/visitor/ExprFolder.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/Codifier.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/pat/PatTycker.java
base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/resources/literate/syntax.aya.md
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java

Fixed:
* Missing type hint on `Pattern.Bind`

Maybe a Fix

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/concrete/visitor/ExprFolder.java
base/src/main/java/org/aya/concrete/visitor/PatternFolder.java
base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
cli/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
lsp/src/main/java/org/aya/lsp/actions/ComputeSignature.java
lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
lsp/src/main/java/org/aya/lsp/utils/Resolver.java

Fold with types

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/PAppTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/EndoTerm.java
base/src/main/java/org/aya/core/visitor/VarConsumer.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/Codifier.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/LittleTyper.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/java/org/aya/cubical/PathTest.java
base/src/test/resources/failure/tyck/issues/issue697.aya.txt
base/src/test/resources/literate/hoshino-said.aya.md

Refactor + implement binary path

---

base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/distill/CoreDistiller.java

Fix pretty print

---

pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/latex/TeXStylist.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/md/MdStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/ClosingStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/DebugStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringStylist.java
pretty/src/main/java/org/aya/pretty/backend/terminal/DocTermPrinter.java
pretty/src/main/java/org/aya/pretty/backend/terminal/UnixTermStylist.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/test/java/org/aya/pretty/DocStringPrinterTest.java
pretty/src/test/java/org/aya/pretty/HtmlStyleTest.java
pretty/src/test/java/org/aya/pretty/MdStyleTest.java

Bullet/Ordered List

---

base/src/main/java/org/aya/core/def/PrimDef.java
cli/src/main/java/org/aya/cli/repl/ReplCompiler.java

Allow prim redefinition in repl mode.

fix(repl): allow prim redefinition in repl

---

pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/Cursor.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/test/java/org/aya/pretty/DocStringPrinterTest.java
pretty/src/test/java/org/aya/pretty/HtmlStyleTest.java
pretty/src/test/java/org/aya/pretty/MdStyleTest.java

Markdown is already easy to read in plain text format.

Just use markdown list for plain text backend

---

base/src/test/resources/success/src/Forall.aya
cli/src/main/java/org/aya/cli/parse/AyaGKProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Simplify: Forall

---

base/src/main/java/org/aya/core/def/CtorDef.java
base/src/main/java/org/aya/core/def/DataDef.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/pat/PatUnify.java
base/src/main/java/org/aya/core/term/PartialTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/visitor/EndoTerm.java
base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/env/MapLocalCtx.java
base/src/main/java/org/aya/tyck/env/SeqLocalCtx.java
base/src/main/java/org/aya/tyck/error/HoleProblem.java
base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/failure/patterns/issues/issue302.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-confl.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-reduce.aya.txt
base/src/test/resources/success/common/src/Arith/Int.aya
base/src/test/resources/success/common/src/Data/FiniteMultiSet/Core.aya
base/src/test/resources/success/common/src/Spaces/Join/Core.aya
base/src/test/resources/success/common/src/Spaces/Susp/Core.aya
base/src/test/resources/success/src/AsPattern.aya
base/src/test/resources/success/src/Issues/595.aya
base/src/test/resources/success/src/Termination.aya

Now, unification will unify concall dataargs so metas inside will be solved.
Co-authored-by: @HoshinoTented

Fix unification bugs

---

base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/test/java/org/aya/experiments/CommonMarkTest.java
base/src/test/resources/literate/hoshino-said.aya.md
cli/src/main/java/org/aya/cli/literate/AyaMdParser.java

Initial support for markdown lists

---

base/src/main/java/org/aya/distill/BaseDistiller.java
base/src/main/java/org/aya/distill/ConcreteDistiller.java
base/src/main/java/org/aya/distill/CoreDistiller.java
base/src/main/java/org/aya/ref/GenerateKind.java
base/src/main/java/org/aya/ref/LocalVar.java
base/src/main/java/org/aya/tyck/error/FieldError.java
cli/src/main/java/org/aya/cli/literate/FaithfulDistiller.java
pretty/src/main/java/org/aya/pretty/backend/html/HtmlConstants.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Styles.java
pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java
pretty/src/main/java/org/aya/pretty/style/AyaStyleKey.java
tools/src/main/java/org/aya/util/error/SourcePos.java

Improve literate backend again

---

cli/src/main/java/org/aya/cli/literate/AyaMdParser.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/md/MdStyle.java
pretty/src/main/java/org/aya/pretty/backend/md/MdStylist.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/test/java/org/aya/pretty/DocStringPrinterTest.java
pretty/src/test/java/org/aya/pretty/MdStyleTest.java

Improve literate backend for vuepress

---

base/src/main/java/org/aya/concrete/remark/CodeAttrProcessor.java
base/src/main/java/org/aya/concrete/remark/Literate.java
base/src/test/resources/literate/hoshino-said.aya.md
cli/src/main/java/org/aya/cli/literate/AyaMdParser.java
pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java

More markdown elements

---

base/reflect-config.txt

fix https://github.com/aya-prover/aya-dev/issues/821
bors r+

nativeimg: update reflect-config

---

base/reflect-config.txt

nativeimg: update reflect-config again for latest main

---

buildSrc/src/main/groovy/org/aya/gradle/CommonTasks.groovy

bors r+
fix https://github.com/aya-prover/aya-dev/issues/809

nativeimg: include missing resource

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/CubicalError.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/error/UnifyInfo.java
base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java

Improve unify error reports: add `UnifyInfo`

---

base/src/main/java/org/aya/concrete/stmt/UseHide.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/context/ModuleExport.java

Try to fix graalvm error caused by `Tuple2`

---

base/reflect-config.txt

build: fix graalvm error

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/main/java/org/aya/tyck/tycker/UnifiedTycker.java
base/src/test/java/org/aya/test/TestRunner.java
base/src/test/resources/failure/patterns/confl-literal.aya.txt
base/src/test/resources/failure/patterns/confl-literal2.aya.txt
base/src/test/resources/failure/patterns/confl.aya.txt
base/src/test/resources/failure/patterns/issues/issue302.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-confl.aya.txt
base/src/test/resources/failure/patterns/issues/issue354-reduce.aya.txt
base/src/test/resources/failure/patterns/issues/issue366.aya.txt
base/src/test/resources/failure/patterns/literal-conf.aya.txt
base/src/test/resources/failure/tyck/lam-param-type-mismatch.aya.txt
base/src/test/resources/success/common/src/Logic/PropTrunc.aya

+ Reused some code
+ Proved some properties about `PropTrunc` so the file is not embarrassingly blank
+ Updated some outdated confluence check error messages

Random improvements listed in the description

---

base/src/main/java/org/aya/core/term/SigmaTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/BadExprError.java
base/src/test/resources/failure/tyck/want-but-no.aya.txt

Cherry-pick from an ongoing refactoring

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/PositivityError.java
base/src/test/resources/failure/tyck/positivity.aya
base/src/test/resources/failure/tyck/positivity.aya.txt

fix https://github.com/aya-prover/aya-dev/issues/838

tyck: add positivity check

---

base/src/main/java/org/aya/core/visitor/PatTraversal.java
base/src/main/java/org/aya/prettier/ConcretePrettier.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/context/ModuleExport.java
base/src/main/java/org/aya/tyck/pat/TypedSubst.java
base/src/test/java/org/aya/literate/AyaMdParserTest.java
base/src/test/java/org/aya/literate/FaithfulPrettierTest.java
cli/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli/src/main/java/org/aya/cli/literate/HighlightsCollector.java
cli/src/main/java/org/aya/cli/repl/ReplContext.java
cli/src/main/java/org/aya/cli/single/SingleAyaFile.java

Cleaning the meaningless TODOs and finishing some easy TODOs.

Clean TODOs

---

base/src/main/java/org/aya/core/Meta.java
base/src/main/java/org/aya/core/term/MetaTerm.java
base/src/main/java/org/aya/core/visitor/VarConsumer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/tycker/MockedTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/main/java/org/aya/tyck/unify/Unifier.java

This is yet just a refactoring. Cherry-picked from an ongoing big branch.

Add `isType` to meta

---

base/src/main/java/org/aya/core/UntypedParam.java
base/src/main/java/org/aya/core/def/DataDef.java
base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/CoeTerm.java
base/src/main/java/org/aya/core/term/LamTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/core/term/SigmaTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/core/visitor/BetaExpander.java
base/src/main/java/org/aya/core/visitor/EndoTerm.java
base/src/main/java/org/aya/prettier/Codifier.java
base/src/main/java/org/aya/prettier/CorePrettier.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/Result.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/tycker/ConcreteAwareTycker.java
base/src/main/java/org/aya/tyck/tycker/MockedTycker.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/main/java/org/aya/tyck/tycker/UnifiedTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/main/java/org/aya/tyck/unify/Unifier.java
base/src/test/java/org/aya/core/EtaTest.java
base/src/test/java/org/aya/core/PrettierTest.java

Untyped lambdas, make `TermComparator` extend `StatedTycker`

---

.github/README.md
lsp/src/main/shell/aya-lsp.bat
lsp/src/main/shell/aya-lsp.sh

Fix https://github.com/aya-prover/setup-aya/actions/runs/3795865242/jobs/6455407546

README update & fix module name

---

base/src/main/java/org/aya/core/term/InOutTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/src/CubicalSubtype.aya

Implement conversion for `inS`/`outS`, without yet solving ZYF's problem

---

.github/workflows/gradle-check.yml

Generate test reports

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/main/java/org/aya/tyck/tycker/TracedTycker.java
base/src/test/resources/failure/holes/issue420.aya.txt

Do not reuse tycker

---

LICENSE
base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/visitor/EndoPattern.java
base/src/main/java/org/aya/core/Meta.java
base/src/main/java/org/aya/core/def/Def.java
base/src/main/java/org/aya/core/pat/PatMatcher.java
base/src/main/java/org/aya/core/pat/PatToTerm.java
base/src/main/java/org/aya/core/term/PartialTerm.java
base/src/main/java/org/aya/core/term/Term.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/Synthesizer.java
base/src/main/java/org/aya/tyck/env/LocalCtx.java
base/src/main/java/org/aya/tyck/error/FieldError.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/tyck/tycker/UnifiedTycker.java
cli/src/main/java/org/aya/cli/utils/MainArgs.java
cli/src/main/java/org/aya/cli/utils/PicocliUtils.java
lsp/src/main/java/org/aya/lsp/utils/LspArgs.java
tools-repl/src/main/java/org/aya/repl/ReplUtil.java

update something and clean ups...

Happy new year!

---

base/src/main/java/org/aya/core/term/ErrorTerm.java
base/src/main/java/org/aya/tyck/pat/Conquer.java
base/src/test/resources/failure/holes/issue747.aya.txt
base/src/test/resources/failure/holes/pattern-confluence.aya.txt

Better error reporting for holes with conditions.

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/error/HoleProblem.java
base/src/main/java/org/aya/tyck/error/IrrElimProblem.java
base/src/main/java/org/aya/tyck/error/PrimError.java
base/src/main/java/org/aya/tyck/error/UnifyInfo.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/tyck/tycker/PropTycker.java
base/src/main/java/org/aya/tyck/unify/Unifier.java
base/src/test/resources/failure/projection/issues2/issue879.aya
base/src/test/resources/failure/projection/issues2/issue879.aya.txt
base/src/test/resources/failure/struct/proj-fn.aya.txt
base/src/test/resources/failure/struct/universe.aya.txt
base/src/test/resources/failure/tyck/erased.aya.txt
base/src/test/resources/failure/tyck/nonsigma-proj.aya.txt
base/src/test/resources/failure/tyck/nonsigma-tup.aya.txt
base/src/test/resources/failure/tyck/nonstruct-new.aya.txt

Fix #879
See fixed issue for more details

Fix sigma projection checking

---

gradle/deps.properties
note/early-changelog.md

Because it's been a while.
bors r+

Release v0.27

---

.github/workflows/nightly-build.yml

This PR resolves a warning in the nightly build workflow.
bors r+

Improve scripts

---

base/src/main/java/org/aya/concrete/stmt/Command.java
base/src/main/java/org/aya/concrete/stmt/QualifiedID.java
base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
base/src/main/java/org/aya/core/serde/CompiledAya.java
base/src/main/java/org/aya/prettier/BasePrettier.java
base/src/main/java/org/aya/prettier/ConcretePrettier.java
base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/context/EmptyContext.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/context/ModuleExport.java
base/src/main/java/org/aya/resolve/context/ModulePath.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
cli-impl/src/main/java/org/aya/cli/library/ImportResolver.java
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
ide/src/main/java/org/aya/ide/Resolver.java
ide/src/main/java/org/aya/ide/util/ModuleVar.java

Further refactor #887 after #893 
/cc @imkiva @HoshinoTented

Refactor qid refactor round two

---

base/src/main/java/org/aya/core/term/ProjTerm.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/tycker/StatedTycker.java
base/src/main/java/org/aya/tyck/unify/Synthesizer.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/common/src/Data/List/Core.aya
base/src/test/resources/success/common/src/Data/Vec.aya
base/src/test/resources/success/src/Issues/896.aya
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java

Implement #896

---

base/src/test/java/org/aya/literate/HighlighterTest.java
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
parser/src/main/java/org/aya/parser/AyaParserDefinitionBase.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java

Improve LaTeX literate backend

---

base/src/test/java/org/aya/literate/HighlighterTest.java
base/src/test/java/org/aya/literate/HighlighterTester.java
base/src/test/resources/success/src/UnivIR.aya
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
parser/src/main/grammar/AyaPsiLexer.flex

Dedicated token for eols

---

.github/workflows/nightly-build.yml
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/unify/TermComparator.java
base/src/test/resources/success/common/src/Arith/Nat.aya
base/src/test/resources/success/common/src/Arith/Nat/Core.aya
base/src/test/resources/success/common/src/Arith/Nat/Miscellaneous.aya
base/src/test/resources/success/common/src/Arith/Nat/Order.aya
base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
base/src/test/resources/success/common/src/Logic/HLevels.aya
base/src/test/resources/success/common/src/Logic/SetTrunc.aya
base/src/test/resources/success/common/src/Paths.aya

xsamklcsbhjfkvsjdiewfhbrjvkfipokejr2bhfviopwe9f8iugyvrhebopdiuyetwsio9*&^%&*()*&^%$#@$%^&*()

Fix graal, fix an infinite loop in `CallResolver`, implement unify for `MetaLitTerm`

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/prettier/ConcretePrettier.java
base/src/main/java/org/aya/resolve/ResolveInfo.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/context/NoExportContext.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/failure/syntax/duplicate-let-open.aya
base/src/test/resources/failure/syntax/duplicate-let-open.aya.txt
base/src/test/resources/success/src/LetOpenExpr.aya
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Let Open Expr

---

.github/README.md
cli-console/src/main/java/org/aya/cli/console/MainArgs.java
gradle/deps.properties
gradle/wrapper/gradle-wrapper.properties

Gradle upgrade

---

base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/test/java/org/aya/tyck/PatCCTest.java
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
tools/src/main/java/module-info.java
tools/src/main/java/org/aya/util/tyck/MCT.java

Slightly improve MCTs

---

base/src/test/resources/success/common/src/Arith/Nat/Encoding.aya
base/src/test/resources/success/common/src/Arith/Ordinal.aya
base/src/test/resources/success/common/src/Paths.aya
base/src/test/resources/success/common/src/Relation/Formula.aya

Improve library

---

base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/test/resources/failure/patterns/issues/issue281.aya.txt
base/src/test/resources/failure/patterns/issues/issue319.aya.txt
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
cli-impl/src/main/java/org/aya/cli/render/vscode/VscColorTheme.java
tools/src/main/java/org/aya/util/tyck/pat/Indexed.java

Use latest Kala APIs, smaller fuel so the error message does not go crazy...

Kala improvements

---

base/src/main/java/org/aya/concrete/stmt/decl/TeleDecl.java
base/src/main/java/org/aya/generic/Constants.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/test/resources/success/src/AnonymousExample.aya
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
cli-impl/src/main/java/org/aya/cli/parse/ModifierParser.java
cli-impl/src/test/java/org/aya/cli/ModifierParserTest.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

Anonymous examples

---

base/src/main/java/org/aya/core/visitor/Expander.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/test/resources/failure/terck/non-term.aya.txt
base/src/test/resources/success/common/src/Data/FiniteMultiSet/Core.aya
base/src/test/resources/success/common/src/Data/Vec.aya

Really not sure what is the best solution here.
The current implementation is very hacky...
Based on #915.

Unfold before termination check!

---

base/src/main/java/org/aya/concrete/visitor/ExprFolder.java
base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
base/src/test/resources/success/common/src/Data/Option.aya
base/src/test/resources/success/common/src/Data/Option/Core.aya
base/src/test/resources/success/common/src/Data/Option/Syntax.aya
base/src/test/resources/success/common/src/Logic/PropTrunc.aya

Fixed something in stdlib and removed TODiDs.

Stdlib and TODOs

---

base/reflect-config.txt
buildSrc/src/main/groovy/org/aya/gradle/CommonTasks.groovy
cli-console/reflect-config.txt
cli-impl/.gitignore
cli-impl/build.gradle.kts
cli-impl/reflect-config.txt

Fix native image build

---

base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
base/src/main/java/org/aya/tyck/unify/Unifier.java
base/src/test/resources/success/common/src/TypeTheory/Thorsten.aya
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf

1. Syntax of data infix
2. Library update

Add more stuffs

---

base/reflect-config.txt
base/src/main/java/org/aya/resolve/context/ModuleName.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/main/java/org/aya/cli/single/SingleFileCompiler.java

Waiting for some other commits to fill this PR...

Fix: graal build

---

buildSrc/src/main/groovy/org/aya/gradle/JFlexTask.groovy
gradle/deps.properties
note/early-changelog.md
parser/src/main/grammar/AyaPsiLexer.flex
pretty/src/main/java/org/aya/pretty/doc/Docile.java
pretty/src/main/java/org/aya/pretty/error/LineColSpan.java
tools/src/main/java/org/aya/util/error/WithPos.java

Release 0.28

---

base/src/test/resources/failure/syntax/overlap-def.aya
base/src/test/resources/failure/syntax/overlap-def.aya.txt
base/src/test/resources/success/common/src/Arith/Bool.aya
base/src/test/resources/success/common/src/Arith/Bool/Core.aya
base/src/test/resources/success/common/src/Arith/Bool/Properties.aya
base/src/test/resources/success/common/src/Arith/Fin/Core.aya
base/src/test/resources/success/common/src/Arith/Fin/Properties.aya
base/src/test/resources/success/common/src/Arith/Nat/Core.aya
base/src/test/resources/success/common/src/Arith/Nat/Equality.aya
base/src/test/resources/success/common/src/Arith/Nat/Order.aya
base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
base/src/test/resources/success/common/src/Logic/Dec.aya
base/src/test/resources/success/common/src/Logic/False.aya
base/src/test/resources/success/common/src/Logic/Reflect.aya
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java

* `Reflect` (Coq style)
* `=? : Nat -> Nat -> Bool` and its properties
* more lemmas for `Bool`
* an error for `overlap def foo => bar`
The last change looks lonely if I create a new PR for it, so I put them together.

More Stdlib + Misc

---

base/src/main/java/org/aya/resolve/context/NoExportContext.java
base/src/main/java/org/aya/resolve/context/PhysicalModuleContext.java

Java's Override doesn't work!!

---

cli-impl/src/main/java/org/aya/cli/render/RenderOptions.java
ide-lsp/src/main/java/org/aya/lsp/models/ServerOptions.java
ide-lsp/src/main/java/org/aya/lsp/models/ServerRenderOptions.java
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide-lsp/src/test/java/org/aya/lsp/LspTest.java
ide-lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java

Make LSP Colorful Again

---

base/src/main/java/module-info.java
base/src/main/java/org/aya/concrete/remark/FencedBlock.java
base/src/main/java/org/aya/concrete/remark/frontmatter/YamlFrontMatter.java
base/src/test/resources/literate/syntax.aya.md
cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
pretty/src/main/java/org/aya/pretty/doc/Language.java

- fix #950 
- added yaml frontmatter support

Literate improvement

---

cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java

```
> data Unit | unit
data Unit : Type 0
| unit
> data What | f (Unit -> Unit)
data What | f (Unit -> Unit)data What : Type 0
| f (_5 : Unit → Unit)
> :t Unit
In file <stdin>:1:0 ->
1 │   Unit
│   ╰──╯
Error: The name `Unit' is not defined in the current scope
Failed to get expression type
> 
```

Merge Carefully

---

.github/README.md
gradle/deps.properties
settings.gradle.kts

Upgrade deps, update readme

---

cli-impl/src/main/java/org/aya/cli/parse/AyaParserImpl.java
cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
gradle/deps.properties
parser/src/main/java/org/aya/parser/GenericNode.java

This PR replaces `MarkerNode::text` with a dynamically computed string slice.

Upgrade upstream

---

base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java

By using `LocalVar::definition`

Simplify `Context::bind`

---

base/src/main/java/org/aya/core/def/PrimDef.java
base/src/main/java/org/aya/core/meta/Meta.java
base/src/main/java/org/aya/core/meta/MetaInfo.java
base/src/main/java/org/aya/core/pat/Pat.java
base/src/main/java/org/aya/core/repr/AyaShape.java
base/src/main/java/org/aya/core/repr/CodeShape.java
base/src/main/java/org/aya/core/serde/SerPat.java
base/src/main/java/org/aya/core/serde/SerTerm.java
base/src/main/java/org/aya/core/serde/Serializer.java
base/src/main/java/org/aya/core/term/IntervalTerm.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/core/term/PiTerm.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/tyck/unify/Unifier.java

Use `enum` singletons, improve prim code

Cherry-pick from cartesian-kan-ops development

---

base/src/main/java/org/aya/core/visitor/BetaExpander.java

Follow up fixes

---

.github/README.md
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/Result.java

This is just a first step. We may also do it in conversion check

Lazily compute types on demand

---

base/src/main/java/org/aya/concrete/GenericAyaFile.java
base/src/main/java/org/aya/concrete/remark/AyaLiterate.java
base/src/main/java/org/aya/concrete/remark/CodeOptions.java
cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
tools-md/src/main/java/org/aya/literate/Literate.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java

- Rename (`CommonCode` -> `InlineCode`, `CommonCodeBlock` -> `CodeBlock`, for consistency with `Doc`)
- Fix #969 
bors merge

fix: do not print `aya-hidden` (#969)

---

gradle/deps.properties

* New methods: `(Consumers|Functions|Predicates)::(tupled|untupled)`;
* New methods `Functions::curried` and `Functions::uncurried`;
* New API: `StringFormat` ([Documents (Chinese)](https://github.com/Glavo/kala-common/blob/main/docs/zh/StringFormat.md)).

KALA: upgrade to 0.66.0

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/stmt/Command.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/main/java/org/aya/core/serde/SerDef.java
base/src/main/java/org/aya/core/term/PathTerm.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/test/java/org/aya/experiments/CommonMarkTest.java
base/src/test/java/org/aya/literate/HighlighterTester.java
base/src/test/java/org/aya/pretty/error/PrettyErrorTest.java
cli-impl/src/main/java/org/aya/cli/render/vscode/VscColorTheme.java
gradle/deps.properties
ide-lsp/src/main/java/org/aya/lsp/models/ServerOptions.java
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
note/early-changelog.md
pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
pretty/src/main/java/org/aya/pretty/error/PrettyError.java
tools-md/src/main/java/org/aya/literate/LiterateConsumer.java
tools-repl/src/main/java/org/aya/repl/CmdCompleter.java
tools-repl/src/main/java/org/aya/repl/CommandManager.java
tools/src/main/java/org/aya/util/tyck/OrgaTycker.java

Release 0.29

---

base/src/main/java/org/aya/concrete/Expr.java
base/src/main/java/org/aya/concrete/desugar/Desugarer.java
base/src/main/java/org/aya/concrete/stmt/Stmt.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/resources/success/src/Issues/963.aya

`LetOpen` was desugared during resolving by mistake, but it is good.

Fix some bad code

---

gradle/deps.properties

* New API: `Option::orElse(Option)`
* Fix some bugs

KALA: upgrade to 0.67.0

---

base/src/main/java/org/aya/concrete/GenericAyaFile.java
base/src/main/java/org/aya/concrete/remark/AyaLiterate.java
base/src/test/resources/success/src/Literate/Syntax.aya.md
cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
tools-md/build.gradle.kts
tools-md/src/main/java/org/aya/literate/Literate.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java
tools-md/src/main/java/org/aya/literate/parser/InterestingLanguage.java
tools-md/src/test/java/org/aya/literate/MarkdownTest.java

- Perfectly resolved #950
- Removed some hacks introduced in #970

Parse only selected languages in markdown

---

.github/workflows/commit-check.yml
.github/workflows/gradle-check.yml
base/reflect-config.txt
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java

Let's try the merge queue with this simple PR

Fix native-image build

---

cli-impl/src/main/java/org/aya/cli/library/source/LibraryOwner.java
cli-impl/src/test/java/org/aya/cli/LibraryGraphTest.java

I hope these utils are helpful in solving #759.
TODO: do we really need those tests?

Libary Dependency Graph

---

base/src/main/java/org/aya/concrete/Pattern.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
tools/src/main/java/org/aya/util/tyck/pat/ClassifierUtil.java

bors r+
Need to port these to anqur...

Extract some classifier code into tools

---

pretty/src/main/java/org/aya/pretty/doc/Doc.java

More wrapper

---

.github/workflows/nightly-build.yml

Use graalvm with Java 20

---

cli-impl/src/main/java/org/aya/cli/parse/AyaParserImpl.java
gradle/deps.properties
note/early-changelog.md

Upgrade deps

---

.github/workflows/extract-version.yaml

Cherry pick from #996

---

.github/workflows/nightly-build.yaml
build.gradle.kts
buildSrc/src/main/groovy/org/aya/gradle/CommonTasks.groovy
ide-lsp/build.gradle.kts

Fix native image nightly build

---

buildSrc/src/main/groovy/org/aya/gradle/GenerateReflectionConfigTask.groovy
buildSrc/src/main/groovy/org/aya/gradle/JdkUrls.java
ide-lsp/build.gradle.kts

Build system improvements

---

base/src/main/java/org/aya/core/repr/AyaShape.java
base/src/main/java/org/aya/core/repr/CodeShape.java
base/src/main/java/org/aya/core/repr/ParamShape.java
base/src/main/java/org/aya/core/repr/PatShape.java
base/src/main/java/org/aya/core/repr/ShapeMatcher.java
base/src/main/java/org/aya/core/repr/TermShape.java
base/src/test/java/org/aya/repr/ShapeMatcherTest.java

Leftover #1003

---

.gitignore
base/src/test/java/org/aya/literate/LiterateFaithfulPrettierTest.java
cli-console/src/main/java/org/aya/cli/console/Main.java
cli-console/src/main/java/org/aya/cli/console/MainArgs.java
cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/FlclFaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/FlclToken.java
cli-impl/src/main/java/org/aya/cli/literate/LiterateFaithfulPrettier.java
cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
cli-impl/src/main/java/org/aya/cli/parse/AyaParserImpl.java
cli-impl/src/main/java/org/aya/cli/parse/FlclParser.java
cli-impl/src/main/java/org/aya/cli/parse/ParserUtil.java
cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
gradle/libs.versions.toml
parser/.gitignore
parser/build.gradle.kts
parser/src/main/gen/org/aya/parser/FlclPsiElementTypes.java
parser/src/main/gen/org/aya/parser/FlclPsiParser.java
parser/src/main/grammar/FlclPsiLexer.flex
parser/src/main/grammar/FlclPsiParser.bnf
parser/src/main/java/org/aya/parser/AyaParserDefinitionBase.java
parser/src/main/java/org/aya/parser/FlclLanguage.java
parser/src/main/java/org/aya/parser/FlclParserDefinition.java
parser/src/main/java/org/aya/parser/ParserDefBase.java
tools/src/main/java/org/aya/util/error/SourceFileLocator.java

Aya quality fake literate

---

cli-console/src/main/java/org/aya/cli/console/Main.java
cli-console/src/main/java/org/aya/cli/console/MainArgs.java
cli-impl/src/main/java/org/aya/cli/literate/FlclToken.java
cli-impl/src/main/java/org/aya/cli/parse/FlclParser.java
parser/src/main/grammar/FlclPsiLexer.flex
pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java

Fix nightly build, improve whitespace handling

---

cli-console/src/main/java/org/aya/cli/console/Main.java
gradle/libs.versions.toml

bors r+
Sorry that I broke everything

Some cli fixes

---

base/src/main/java/org/aya/tyck/pat/PatternTycker.java
gradle/libs.versions.toml
ide/src/main/java/org/aya/ide/action/ComputeSignature.java
ide/src/main/java/org/aya/ide/action/Rename.java
parser/src/main/grammar/FlclPsiLexer.flex
pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
pretty/src/main/java/org/aya/pretty/backend/string/ClosingStylist.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
pretty/src/main/java/org/aya/pretty/error/PrettyError.java

Dependencies

---

base/src/main/java/org/aya/tyck/error/Goal.java

Fix #1013 
Thanks @dannypsnl for reporting this :tada:

Freeze holes in context

---

base/src/main/java/org/aya/tyck/pat/PatternTycker.java

Do not unify in case of errors

---

gradle/libs.versions.toml

version: release 0.30

---

.github/README.md
.github/workflows/commit-check.yaml
.github/workflows/extract-version.yaml
.github/workflows/gradle-check.yaml
.github/workflows/nightly-build.yaml
cli-impl/src/test/java/org/aya/test/TestRunner.java
gradle/libs.versions.toml
tools/src/main/java/org/aya/util/error/SourceFile.java

Upgrade many things in deps and ci

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/normalize/PatMatcher.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatUnify.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/main/java/org/aya/tyck/tycker/AppTycker.java
base/src/main/java/org/aya/unify/Synthesizer.java
base/src/main/java/org/aya/unify/TermComparator.java
cli-console/src/main/java/org/aya/cli/console/AnsiReporter.java
cli-console/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli-impl/src/test/resources/negative/PatCohError.txt
cli-impl/src/test/resources/shared/src/data/Interval.aya
cli-impl/src/test/resources/shared/src/data/Vec.aya
jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
syntax/src/main/java/org/aya/syntax/compile/JitCon.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
syntax/src/main/java/org/aya/syntax/core/pat/PatToTerm.java
syntax/src/main/java/org/aya/syntax/core/term/call/ConCallLike.java

Tyck fixes

---

base/src/main/java/org/aya/tyck/ExprTycker.java
gradle/libs.versions.toml
jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
jit-compiler/src/test/java/RedBlackTreeTest.java
syntax/src/main/java/org/aya/syntax/core/term/repr/ListTerm.java

Faster!
Using `ImmVector` (default impl of ImmSeq):
```
0: Done in 24ms
1: Done in 19ms
2: Done in 17ms
3: Done in 15ms
4: Done in 15ms
Average: Done in 18ms
[ 0, 0, 0, 0, 0, 1, 1, 2, 2, 2, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 6, 7, 8, 9, 10, 10, 10, 11, 11, 11, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 16, 17, 18, 18, 19, 19, 19, 19, 20, 20, 21, 23, 23, 24, 24, 24, 24, 25, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 29, 29, 30, 31, 31, 32, 33, 33, 34, 34, 35, 36, 36, 37, 37, 37, 38, 38, 41, 41, 42, 42, 43, 44, 44, 44, 45, 45, 45, 45, 45, 45, 46, 47, 47, 47, 47, 47, 48, 48, 49, 50, 50, 51, 52, 53, 55, 56, 56, 57, 57, 57, 57, 59, 59, 59, 59, 59, 60, 61, 61, 62, 62, 62, 62, 62, 63, 63, 63, 64, 64, 64, 64, 65, 65, 66, 66, 66, 66, 67, 67, 68, 69, 69, 69, 69, 70, 70, 71, 72, 73, 73, 74, 74, 76, 76, …
```

Use persistent data structure from kala

---

base/src/main/java/org/aya/tyck/StmtTycker.java
cli-impl/src/test/resources/success/src/Test.aya
syntax/src/main/java/org/aya/syntax/core/Closure.java
syntax/src/main/java/org/aya/syntax/core/def/Signature.java
syntax/src/main/java/org/aya/syntax/core/term/PiTerm.java

Fix #1060 (untested yet) and fix #1061

Push telescopes

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/HoleProblem.java
base/src/main/java/org/aya/tyck/error/UnifyInfo.java
base/src/main/java/org/aya/unify/Unifier.java
base/src/test/java/org/aya/tyck/TyckTest.java
cli-impl/src/test/java/org/aya/test/TestRunner.java
cli-impl/src/test/resources/shared/src/data/List.aya
cli-impl/src/test/resources/success/src/Guide.aya
jit-compiler/src/test/java/RedBlackTreeTest.java
syntax/src/main/java/org/aya/syntax/core/def/ConDef.java
syntax/src/main/java/org/aya/syntax/core/term/call/ConCall.java
syntax/src/main/java/org/aya/syntax/core/term/call/DataCall.java

As title, trying to make an example work...

Revert some code deletion, delete some unused code

---

base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
base/src/test/java/org/aya/tyck/PatternTyckTest.java
jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
jit-compiler/src/main/java/org/aya/compiler/FileSerializer.java
jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
jit-compiler/src/main/java/org/aya/compiler/PrimSerializer.java
jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
jit-compiler/src/test/java/CompileTest.java

This PR removes some useless abstraction of jit-compiler and makes `AbstractSerializer` smaller.

Refactor of jit-compiler

---

base/src/main/java/org/aya/normalize/Finalizer.java
base/src/main/java/org/aya/normalize/PatMatcher.java
base/src/main/java/org/aya/tyck/error/ClausesProblem.java
base/src/main/java/org/aya/tyck/error/Goal.java
base/src/main/java/org/aya/tyck/error/UnifyInfo.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/tycker/Stateful.java
base/src/main/java/org/aya/unify/Unifier.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
cli-impl/src/test/resources/negative/PatCohError.txt
cli-impl/src/test/resources/shared/src/data/vec/base.aya
cli-impl/src/test/resources/shared/src/data/vec/properties.aya
cli-impl/src/test/resources/shared/src/paths.aya
syntax/src/main/java/org/aya/prettier/BasePrettier.java
syntax/src/main/java/org/aya/prettier/FindUsage.java
syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java

https://github.com/aya-prover/aya-dev/blob/6c5ec7f9601555f9e3a006631532d8b17f34c5a8/base/src/test/resources/success/common/src/Data/Vec.aya#L28-L29
This is no longer an issue

Why did we play Haruhikage??

---

base/src/main/java/org/aya/normalize/Normalizer.java
cli-impl/src/test/resources/shared/src/data/fmset/base.aya

Makes fmset/base.aya work

---

base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
syntax/src/main/java/org/aya/prettier/BasePrettier.java
syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/term/call/RuleReducer.java
tools/src/main/java/org/aya/util/reporter/Problem.java

Fix checkCon return type treatment

---

gradle/libs.versions.toml
note/early-changelog.md

Release v0.32

---

base/src/main/java/org/aya/resolve/ResolveInfo.java
cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
cli-impl/src/test/resources/shared/src/relation/binary/path.aya
jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
jit-compiler/src/test/java/CompileTest.java
jit-compiler/src/test/java/MiscTest.java

Fix module name serialization

---

base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
cli-impl/src/test/resources/negative/ScopeError.txt
cli-impl/src/test/resources/shared/src/prelude.aya
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java
jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java

Some bug fixes

---

gradle/libs.versions.toml
producer/src/main/java/org/aya/producer/AyaProducer.java
producer/src/main/java/org/aya/producer/ParserUtil.java

Now we have an extra Kotlin dependency... What a shame

Upgrade build util

---

base/build.gradle.kts
base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
cli-impl/src/test/resources/success/src/Test.aya
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
syntax/src/main/java/org/aya/prettier/Tokens.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java

Coercive subtyping fixes + cherry pick from classes

---

base/src/main/java/org/aya/tyck/ExprTycker.java
gradle/libs.versions.toml
jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
syntax/src/main/java/org/aya/syntax/core/term/ClassCastTerm.java
syntax/src/main/java/org/aya/syntax/core/term/call/MemberCall.java

* Add `ClassCastTerm#make` that flattens the nesting cast term.
* Use `ClassCastTerm#make` everywhere.
* Use `MemberCall#make` everywhere.

Add something without thinking

---

base/src/main/java/org/aya/resolve/salt/Desalt.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java

Simplify concrete

---

jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
syntax/src/main/java/org/aya/syntax/core/Closure.java
tools/src/main/java/org/aya/util/error/Global.java

Usage analy in jit compiler

---

base/src/main/java/org/aya/tyck/ArgsComputer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/StmtTycker.java

Cherry pick from class resolver

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/unify/Synthesizer.java
base/src/main/java/org/aya/unify/TermComparator.java
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/term/ProjTerm.java

Projection Typecheck

---

base/src/main/java/org/aya/normalize/Normalizer.java
cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
ide-lsp/build.gradle.kts
syntax/src/main/java/org/aya/syntax/core/term/AppTerm.java
syntax/src/main/java/org/aya/syntax/core/term/ClassCastTerm.java
syntax/src/main/java/org/aya/syntax/core/term/LamTerm.java
syntax/src/main/java/org/aya/syntax/core/term/ProjTerm.java
syntax/src/main/java/org/aya/syntax/core/term/call/Callable.java
syntax/src/main/java/org/aya/syntax/core/term/call/MemberCall.java
syntax/src/main/java/org/aya/syntax/core/term/call/MetaCall.java
syntax/src/main/java/org/aya/syntax/core/term/marker/BetaRedex.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/EqTerm.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/PAppTerm.java

Fix head normalization

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
base/src/main/java/org/aya/tyck/tycker/Contextful.java
base/src/main/java/org/aya/tyck/tycker/Stateful.java
syntax/src/main/java/org/aya/syntax/ref/LocalCtx.java
syntax/src/main/java/org/aya/syntax/ref/MapLocalCtx.java
syntax/src/main/java/org/aya/syntax/ref/SeqLocalCtx.java

Fix #1039
Completely untested, need `hcomp` to test

Add `connect`, `disconnect` APIs, change related functions to perform necessary cleanups

---

base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/salt/ExprBinParser.java
base/src/main/java/org/aya/tyck/ExprTycker.java
cli-impl/src/test/java/org/aya/test/LibraryTest.java
cli-impl/src/test/resources/shared/src/arith/bool/base.aya
cli-impl/src/test/resources/shared/src/arith/bool/properties.aya
cli-impl/src/test/resources/shared/src/data/either.aya
cli-impl/src/test/resources/shared/src/data/either/base.aya
cli-impl/src/test/resources/shared/src/data/list/base.aya
cli-impl/src/test/resources/shared/src/data/list/properties.aya
cli-impl/src/test/resources/shared/src/data/vec/properties.aya
cli-impl/src/test/resources/shared/src/relation/unary/negation.aya
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/ref/LocalVar.java

Add more stuff to standard library and find some bugs

More stdlib

---

base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/error/ClassError.java
base/src/main/java/org/aya/tyck/error/CubicalError.java
base/src/main/java/org/aya/tyck/error/MetaVarError.java
base/src/main/java/org/aya/tyck/error/PrimError.java
base/src/main/java/org/aya/tyck/error/TyckOrderError.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatUnify.java
base/src/main/java/org/aya/unify/Unifier.java
cli-impl/src/test/java/org/aya/test/fixtures/ClassError.java
cli-impl/src/test/resources/negative/ClassError.txt
cli-impl/src/test/resources/negative/ExprTyckError.txt
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/core/pat/BindEater.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
syntax/src/main/java/org/aya/syntax/core/pat/PatMatcher.java

More precise, and resolve a couple of TODOs. Some code is copied from old Aya

A bunch of error report improvements

---

base/src/main/java/org/aya/normalize/Finalizer.java
base/src/main/java/org/aya/tyck/ArgsComputer.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
cli-impl/src/test/resources/success/src/Test.aya
note/jit.md

Applying to a meta-typed term is ok, avoid reporting the same unsolved meta many times

---

base/src/main/java/org/aya/tyck/ArgsComputer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
cli-impl/src/test/resources/success/src/Test.aya
syntax/src/main/java/org/aya/syntax/core/term/DepTypeTerm.java
syntax/src/main/java/org/aya/syntax/ref/MetaVar.java

Better code to deal with metavar refinements

---

base/src/main/java/org/aya/normalize/Finalizer.java
base/src/main/java/org/aya/tyck/ArgsComputer.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/TyckState.java
base/src/main/java/org/aya/unify/DoubleChecker.java
base/src/main/java/org/aya/unify/Unifier.java
cli-impl/src/test/resources/shared/src/data/either.aya
cli-impl/src/test/resources/shared/src/data/list/properties.aya
cli-impl/src/test/resources/shared/src/data/sum.aya
cli-impl/src/test/resources/shared/src/data/sum/base.aya
cli-impl/src/test/resources/success/src/PLFA.aya
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/term/call/MetaCall.java
syntax/src/main/java/org/aya/syntax/ref/MetaVar.java

Code that are not about matches

Cherry picks from match term

---

base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/unify/Synthesizer.java
jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
syntax/src/main/java/org/aya/syntax/core/pat/PatMatcher.java
syntax/src/main/java/org/aya/syntax/core/pat/PatToTerm.java
syntax/src/main/java/org/aya/syntax/core/pat/TypeEraser.java

Cherry pick erased patterns from match PR

---

base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/primitive/ShapeMatcher.java
base/src/main/java/org/aya/resolve/StmtResolvers.java
base/src/main/java/org/aya/resolve/salt/Desalt.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/terck/CallResolver.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/IApplyConfl.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/main/java/org/aya/unify/Synthesizer.java
base/src/test/java/org/aya/syntax/core/PrettierTest.java
base/src/test/java/org/aya/tyck/TyckTest.java
cli-impl/src/test/resources/success/src/Match.aya
jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/prettier/Tokens.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/core/def/FnDef.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
syntax/src/main/java/org/aya/syntax/core/term/MatchTerm.java
syntax/src/main/java/org/aya/syntax/core/term/Term.java

Implement match term, its type checking and serialization

Introduce MathTerm

---

gradle/libs.versions.toml
note/early-changelog.md

Release 0.35

---

base/src/main/java/org/aya/normalize/Finalizer.java
base/src/main/java/org/aya/normalize/Normalizer.java
base/src/main/java/org/aya/tyck/Jdg.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt

TRO in normalizer, report fewer unsolved meta errors

---

base/src/main/java/org/aya/resolve/ResolveInfo.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
cli-impl/src/main/java/org/aya/cli/library/source/LibrarySource.java
cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
ide-lsp/src/test/java/org/aya/lsp/LspTest.java
jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java

Unimport and correctly loading libraries in REPL

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
base/src/main/java/org/aya/tyck/tycker/AppTycker.java
base/src/main/java/org/aya/tyck/tycker/Contextful.java
base/src/main/java/org/aya/unify/DoubleChecker.java
base/src/main/java/org/aya/unify/Synthesizer.java
base/src/main/java/org/aya/unify/TermComparator.java

fix https://github.com/aya-prover/aya-dev/issues/1201

Use try-with-resource for cleanup

---

base/src/main/java/org/aya/tyck/ArgsComputer.java
base/src/main/java/org/aya/tyck/error/ClassError.java
base/src/main/java/org/aya/tyck/error/LicitError.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/unify/Synthesizer.java
cli-impl/src/test/java/org/aya/test/fixtures/ClassError.java
cli-impl/src/test/resources/negative/ClassError.txt
syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java

Correctly report "instance not found" errors

---

base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/resolve/context/EmptyContext.java
base/src/main/java/org/aya/resolve/context/PhysicalModuleContext.java
base/src/main/java/org/aya/resolve/context/ReporterContext.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
base/src/main/java/org/aya/tyck/StmtTycker.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
cli-impl/src/test/resources/shared/src/data/list/properties.aya
cli-impl/src/test/resources/shared/src/data/vec/properties.aya
syntax/src/main/java/org/aya/syntax/ref/QPath.java
tools/src/main/java/org/aya/util/reporter/SuppressingReporter.java

fixes https://github.com/aya-prover/aya-dev/issues/1199

suppress Shadowing

---

base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
cli-console/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
cli-impl/src/test/java/org/aya/test/TestRunner.java
tools/src/main/java/org/aya/util/reporter/CountingReporter.java

Including:
1. If tycking a module took > 1.5 seconds, it'll print the time taken
2. The outputs of negative test cases are combined into a single long line

Improve the cli output of many things

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/MatchMissingReturnsError.java
base/src/main/java/org/aya/unify/Synthesizer.java
cli-impl/src/test/java/org/aya/test/fixtures/ExprTyckError.java
cli-impl/src/test/resources/negative/ExprTyckError.txt
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/core/term/MatchTerm.java

Match term `as returns`

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md

Also https://github.com/leanprover/lean4/commit/133e03ce7f8d1b9c42d2475b4bcbee38521345c8#diff-40c12e558dc7180c7d335a2076efe1fa08e1d9022b4985223ba914463b49032dL10-L18

Update docs with status quo

---

cli-impl/src/test/java/org/aya/test/cli/RenderOptionsTest.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java

Related: https://github.com/markdown-it/markdown-it/issues/1056 and https://github.com/vuejs/vitepress/issues/4426

Fix another markdown generation issue

---

base/src/main/java/org/aya/normalize/Normalizer.java
syntax/src/main/java/org/aya/syntax/core/term/Term.java

Remove a bunch of unnecessary `Term` ops

---

base/src/main/java/org/aya/tyck/ExprTycker.java

Fix The Bug I Wrote

---

base/src/main/java/org/aya/resolve/context/ModuleExport.java
base/src/main/java/org/aya/resolve/error/NameProblem.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
base/src/main/java/org/aya/tyck/tycker/AppTycker.java
base/src/main/java/org/aya/unify/TermComparator.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
cli-impl/src/test/java/org/aya/test/fixtures/ExprTyckError.java
cli-impl/src/test/java/org/aya/test/literate/HighlighterTester.java
cli-impl/src/test/resources/negative/ExprTyckError.txt
ide/src/main/java/org/aya/ide/LspPrimFactory.java
jit-compiler/src/main/java/org/aya/compiler/serializers/PatternSerializer.java
pretty/src/main/java/org/aya/pretty/doc/Doc.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/concrete/stmt/ModuleName.java
syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
tools-kala/src/main/java/org/aya/util/terck/CallMatrix.java
tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java
tools/src/main/java/org/aya/util/ForLSP.java

Fix some of the ridiculous doc comments being rendered incorrectly:

Bug fix & slightly use more markdown doc comments

---

cli-impl/src/test/resources/success/src/Test.aya
parser/src/main/grammar/AyaPsiLexer.flex

Allow `-` and `-->` and `------------------------------------->`

---

base/src/main/java/org/aya/tyck/ExprTycker.java
cli-impl/src/test/resources/success/src/Test.aya

Fix subtyping from path to pi

---

cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java

Fix a bug in literate code generation

---

ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide-lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java

Address https://github.com/aya-prover/intellij-aya/issues/31

Let `registerLibrary` returns the loaded libraries

---

cli-impl/src/main/java/org/aya/cli/library/source/DiskLibraryOwner.java
cli-impl/src/test/resources/shared/src/data/list/properties.aya
cli-impl/src/test/resources/shared/src/relation/binary/nat_cmp.aya
cli-impl/src/test/resources/shared/src/relation/nullary/decidable.aya
syntax/src/main/java/org/aya/syntax/concrete/Expr.java

It should have `srcPath` in `modulePath`

Properly initialize `DiskLibraryOwner`

---

jit-compiler/src/main/java/org/aya/compiler/free/FreeCodeBuilder.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeCodeBuilderImpl.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeOptimizer.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeRunner.java
jit-compiler/src/main/java/org/aya/compiler/free/morphism/free/FreeStmt.java
jit-compiler/src/main/java/org/aya/compiler/serializers/AyaSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/JitTeleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/ModuleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/PatternSerializer.java
jit-compiler/src/test/java/CompileTest.java

Initial optimizer

---

base/src/test/java/org/aya/tyck/TyckTest.java
cli-impl/src/test/resources/shared/src/arith/nat/base.aya
cli-impl/src/test/resources/shared/src/relation/binary/nat_cmp.aya
cli-impl/src/test/resources/success/src/PLFA.aya
cli-impl/src/test/resources/success/src/Pattern.aya
cli-impl/src/test/resources/success/src/STLC.aya
gradle/libs.versions.toml
jit-compiler/src/main/java/org/aya/compiler/free/morphism/source/SourceClassBuilder.java
note/early-changelog.md
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/syntax/compile/CompiledAya.java

Release v0.37

---

base/src/main/java/org/aya/normalize/LetReplacer.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
base/src/main/java/org/aya/tyck/pat/PatBinder.java
base/src/main/java/org/aya/tyck/pat/PatClassifier.java
base/src/main/java/org/aya/tyck/pat/PatternTycker.java
cli-impl/src/test/resources/negative/PatCohError.txt
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/serializers/PatternExprializer.java
syntax/src/main/java/org/aya/syntax/core/def/FnClauseBody.java
syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
tools-kala/src/main/java/org/aya/util/tyck/pat/ClassifierUtil.java
tools-kala/src/main/java/org/aya/util/tyck/pat/PatClass.java

MAY THE FORCE BE WITH YOU

---

base/src/main/java/org/aya/primitive/PrimFactory.java
base/src/main/java/org/aya/primitive/ShapeMatcher.java
base/src/main/java/org/aya/resolve/context/Context.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/test/java/org/aya/tyck/TyckTest.java
cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
ide/src/main/java/org/aya/ide/Resolver.java
jit-compiler/src/main/java/org/aya/compiler/serializers/DataSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/ModuleSerializer.java
jit-compiler/src/main/java/org/aya/compiler/serializers/PrimSerializer.java
syntax/src/main/java/org/aya/syntax/core/RichParam.java
syntax/src/main/java/org/aya/syntax/core/def/DataDef.java
syntax/src/main/java/org/aya/syntax/core/def/PrimDef.java
syntax/src/main/java/org/aya/syntax/core/def/TyckAnyDef.java

Including `DataDef` and `PrimDef`. Also some comments-related changes.

Turn some classes into records

---

base/src/main/java/org/aya/primitive/PrimFactory.java
base/src/main/java/org/aya/resolve/ResolvingStmt.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
ide-lsp/src/test/resources/lsp-test-lib/src/PathPrims.aya
syntax/src/main/java/org/aya/syntax/core/def/PrimDef.java

Also adds partial term in prim, related to #1029

Cherry pick from #1298

---

base/src/main/java/org/aya/resolve/context/Candidate.java
base/src/main/java/org/aya/tyck/error/ClausesProblem.java
base/src/main/java/org/aya/tyck/pat/YouTrack.java
cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
cli-impl/src/main/java/org/aya/cli/render/vscode/ColorTheme.java
cli-impl/src/test/resources/negative/PatCohError.txt
gradle/libs.versions.toml
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide-lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java
jit-compiler/src/main/java/org/aya/compiler/free/FreeJavaResolver.java
producer/src/main/java/org/aya/producer/AyaProducer.java
tools-kala/src/main/java/org/aya/util/reporter/Problem.java
tools-repl/src/main/java/org/aya/repl/CommandArg.java
tools-repl/src/main/java/org/aya/repl/CommandManager.java
tools-repl/src/main/java/org/aya/repl/ReplParser.java

Use `onEach` and refactor some `stream` to `view`

---

base/src/test/java/org/aya/tyck/TyckTest.java
jit-compiler/src/test/java/RedBlackTreeTest.java

mklsxmasklxmlksmxlkmxklsamxklasmxlka

Code changed during plunch

---

base/src/main/java/org/aya/primitive/PrimFactory.java
base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/BadTypeError.java
base/src/main/java/org/aya/tyck/tycker/Stateful.java
base/src/main/java/org/aya/unify/DoubleChecker.java
base/src/main/java/org/aya/unify/Synthesizer.java
base/src/main/java/org/aya/unify/TermComparator.java
base/src/test/java/org/aya/syntax/core/PrettierTest.java
cli-impl/src/test/java/org/aya/test/fixtures/ExprTyckError.java
cli-impl/src/test/resources/negative/ExprTyckError.txt
cli-impl/src/test/resources/shared/src/relation/binary/path.aya
cli-impl/src/test/resources/success/src/Test.aya
jit-compiler/src/main/java/org/aya/compiler/serializers/TermExprializer.java
parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
parser/src/main/gen/org/aya/parser/AyaPsiParser.java
parser/src/main/grammar/AyaPsiParser.bnf
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
syntax/src/main/java/org/aya/prettier/CorePrettier.java
syntax/src/main/java/org/aya/prettier/Tokens.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/core/term/SortTerm.java
syntax/src/main/java/org/aya/syntax/core/term/Term.java
syntax/src/main/java/org/aya/syntax/core/term/marker/Formation.java
syntax/src/main/java/org/aya/syntax/core/term/marker/StableWHNF.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/PartialTerm.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/PartialTyTerm.java

Initial partial element by KonjacSource

---

base/src/main/java/org/aya/tyck/ExprTycker.java
base/src/main/java/org/aya/tyck/error/DoubleCheckError.java
base/src/main/java/org/aya/tyck/error/UnifyInfo.java
base/src/main/java/org/aya/tyck/tycker/Unifiable.java
base/src/main/java/org/aya/unify/DoubleChecker.java
base/src/main/java/org/aya/unify/Unifier.java
syntax/src/main/java/org/aya/syntax/core/term/xtt/DimTerm.java

Improve double checker

---

gradle/libs.versions.toml
note/early-changelog.md

Release 0.38

---

base/build.gradle.kts
build.gradle.kts
cli-console/build.gradle.kts
cli-impl/build.gradle.kts
gradle/libs.versions.toml
ide-lsp/build.gradle.kts
jit-compiler/build.gradle.kts
parser/build.gradle.kts
pretty/build.gradle.kts
syntax/build.gradle.kts
tools-md/build.gradle.kts
tools/build.gradle.kts

Use gradle test suite

---

base/src/main/java/org/aya/resolve/ResolvingStmt.java
base/src/main/java/org/aya/resolve/context/ModuleContext.java
base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
base/src/main/java/org/aya/tyck/StmtTycker.java
base/src/main/java/org/aya/tyck/error/PrimError.java
base/src/main/java/org/aya/tyck/error/TyckOrderError.java
base/src/main/java/org/aya/tyck/error/UnifyError.java
base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
ide-lsp/src/main/java/org/aya/lsp/actions/Completion.java
ide-lsp/src/main/java/org/aya/lsp/actions/ContextWalker.java
ide-lsp/src/main/java/org/aya/lsp/actions/LensMaker.java
ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
ide-lsp/src/test/java/org/aya/lsp/LspTest.java
ide-lsp/src/test/resources/lsp-test-lib/src/HelloWorld.aya
ide/src/main/java/org/aya/ide/action/GotoDefinition.java
ide/src/main/java/org/aya/ide/action/ProjectSymbol.java
ide/src/main/java/org/aya/ide/syntax/SyntaxNodeAction.java
producer/src/main/java/org/aya/producer/AyaProducer.java
syntax/src/main/java/org/aya/generic/stmt/TyckUnit.java
syntax/src/main/java/org/aya/syntax/concrete/Expr.java
syntax/src/main/java/org/aya/syntax/concrete/Named.java
syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/Decl.java
syntax/src/main/java/org/aya/syntax/ref/LocalVar.java

Context Walker and `CompletionItem`

---

base/src/main/java/org/aya/tyck/error/Goal.java
cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
cli-impl/src/test/resources/negative/GoalAndMeta.txt
syntax/src/main/java/org/aya/syntax/core/term/DepTypeTerm.java

Some user interaction changes
